/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.Entity.KhachHang;
import com.mycompany.qlbatdongsan.Entity.SanPhamDuAn;

/**
 *
 * @author HO VAN DAT
 */
public class AddMajorFrame extends javax.swing.JFrame {
    static SanPhamDuAn spda;
    static KhachHang kh;

    public AddMajorFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenHopDong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSPDuAn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblSPDuAn = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        btnKhachHang = new javax.swing.JButton();
        btnSucess = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblSucess = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboLoaiHopDong = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("TẠO MỚI HỢP ĐỒNG");

        jLabel2.setText("Tên hợp đồng");

        jLabel3.setText("Sản phẩm dự án");

        btnSPDuAn.setText("Thêm");
        btnSPDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPDuAnActionPerformed(evt);
            }
        });

        jLabel5.setText("Khách hàng");

        lblSPDuAn.setBackground(new java.awt.Color(204, 204, 204));
        lblSPDuAn.setForeground(new java.awt.Color(204, 204, 204));
        lblSPDuAn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSPDuAn.setEnabled(false);

        lblKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        lblKhachHang.setForeground(new java.awt.Color(204, 204, 204));
        lblKhachHang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblKhachHang.setEnabled(false);

        btnKhachHang.setText("Thêm");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnSucess.setBackground(new java.awt.Color(102, 102, 102));
        btnSucess.setRoundBottonLeft(30);
        btnSucess.setRoundBottonRight(30);
        btnSucess.setRoundTopLeft(30);
        btnSucess.setRoundTopRight(30);

        lblSucess.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblSucess.setForeground(new java.awt.Color(204, 0, 0));
        lblSucess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSucess.setText("Hoàn thành");
        lblSucess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSucessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSucessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSucessMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSucessLayout = new javax.swing.GroupLayout(btnSucess);
        btnSucess.setLayout(btnSucessLayout);
        btnSucessLayout.setHorizontalGroup(
            btnSucessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSucessLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSucessLayout.setVerticalGroup(
            btnSucessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSucessLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblSucess, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jLabel7.setText("Loại Hợp đồng");

        cboLoaiHopDong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSucess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKhachHang)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btnSPDuAn)
                            .addComponent(txtTenHopDong)
                            .addComponent(lblSPDuAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cboLoaiHopDong, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTenHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSPDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnSPDuAn)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKhachHang)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboLoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnSucess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSucessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSucessMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSucessMouseClicked

    private void lblSucessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSucessMouseEntered
        // TODO add your handling code here:
        btnSucess.setBounds(btnSucess.getX() - 5, btnSucess.getY() - 5, btnSucess.getWidth() + 10, btnSucess.getHeight() + 10);
        lblSucess.setBounds(lblSucess.getX(), lblSucess.getY(), lblSucess.getWidth() + 10, lblSucess.getHeight() + 10);
    }//GEN-LAST:event_lblSucessMouseEntered

    private void lblSucessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSucessMouseExited
        // TODO add your handling code here:
        btnSucess.setBounds(btnSucess.getX() + 5, btnSucess.getY() + 5, btnSucess.getWidth() - 10, btnSucess.getHeight() - 10);
        lblSucess.setBounds(lblSucess.getX(), lblSucess.getY(), lblSucess.getWidth() - 10, lblSucess.getHeight() - 10);
    }//GEN-LAST:event_lblSucessMouseExited

    private void btnSPDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPDuAnActionPerformed
        // TODO add your handling code here:
        ShowSPDAFrame showSPDAFrame =new ShowSPDAFrame();
        showSPDAFrame.setVisible(true);
    }//GEN-LAST:event_btnSPDuAnActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        ShowKhachHangFrame showKhachHangFrame = new ShowKhachHangFrame();
        showKhachHangFrame.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMajorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMajorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMajorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMajorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnSPDuAn;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnSucess;
    private javax.swing.JComboBox<String> cboLoaiHopDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblSPDuAn;
    private javax.swing.JLabel lblSucess;
    private javax.swing.JTextField txtTenHopDong;
    // End of variables declaration//GEN-END:variables
}
