/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.QuanLyDuAnDAO;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.utils.XDate;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import com.mycompany.qlbatdongsan.utils.XImage;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author HO VAN DAT
 */
public class AddProjectFrame extends javax.swing.JFrame {

    QuanLyDuAnDAO dao = new QuanLyDuAnDAO();

    /**
     * Creates new form AddProjectFrame
     */
    public AddProjectFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
        setTitle("THÊM DỰ ÁN BẤT ĐỘNG SẢN DVPTP");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    QuanLyDuAn getForm() {
        QuanLyDuAn da = new QuanLyDuAn();
        da.setMaDA(txtMaDuAn.getText());
        da.setTenDA(txtTenDuAn.getText());
        da.setDiaChi(txaDiaChi.getText());
//        if (txtDienTich.getText().isEmpty()) {
//            da.setDienTich(null);
//        } else {
        da.setDienTich(Float.valueOf(txtDienTich.getText()));
        //}
//        if (txtSoGiayPhep.getText().isEmpty()) {
//            da.setSoGiayPhep(0);
//        } else {
        da.setSoGiayPhep(Integer.parseInt(txtSoGiayPhep.getText()));
        //}
//        if (txtNgayCap.getText().isEmpty()) {
//            da.setNgayCap(null);
//        } else {

         da.setNgayCap(XDate.toDate(txtNgayCap.getText(), "yyyy-MM-dd"));
//        }

        da.setNoiCap(txtNoiCap.getText());
        da.setLoaiDA(txtLoaiDuAn.getText());
        da.setMaNVPhuTrach(txtNVPhuTrach.getText());
//        if (txtNgayDang.getText().isEmpty()) {
//            da.setNgayDang(null);
//        } else {
        da.setNgayDang(XDate.toDate(txtNgayDang.getText(), "yyyy-MM-dd"));
        //}
        return da;
    }

    void add() {
        QuanLyDuAn da = getForm();
        try {
            dao.insert(da);
            ProjectFrame.fillTableDA();
            MsgBox.alert(this, "Thêm dự án thành công!");
            this.dispose();
        } catch (Exception e) {
            MsgBox.alert(this, "Đã có lỗi xảy ra!");
            e.printStackTrace();
        }

    }

    void clearForm() {
        QuanLyDuAn da = new QuanLyDuAn();
        setForm(da);
    }

    void setForm(QuanLyDuAn model) {
        txtMaDuAn.setText(model.getMaDA());
        txtTenDuAn.setText(model.getTenDA());
        txaDiaChi.setText(model.getDiaChi());
        txtDienTich.setText(Float.toString(model.getDienTich()));
        txtSoGiayPhep.setText(Float.toString(model.getSoGiayPhep()));
        txtNgayCap.setText(XDate.toString((Date) model.getNgayCap(), "yyyy-MM-dd"));
        txtNoiCap.setText(model.getNoiCap());
        txtLoaiDuAn.setText(model.getLoaiDA());
        txtNVPhuTrach.setText(model.getMaNVPhuTrach());
        txtNgayDang.setText(String.valueOf(model.getNgayDang()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDienTich = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoGiayPhep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoaiDuAn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayDang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoiCap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDiaChi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtMaDuAn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNgayCap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenDuAn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNVPhuTrach = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        txtDienTich.setBackground(new java.awt.Color(153, 153, 153));
        txtDienTich.setText("700");
        txtDienTich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDienTichMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tên dự án");

        txtSoGiayPhep.setBackground(new java.awt.Color(153, 153, 153));
        txtSoGiayPhep.setText("1412");
        txtSoGiayPhep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoGiayPhepMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Địa chỉ");

        txtLoaiDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtLoaiDuAn.setForeground(new java.awt.Color(51, 51, 51));
        txtLoaiDuAn.setText("Đất nền");
        txtLoaiDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoaiDuAnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Số giấy phép");

        txtNgayDang.setBackground(new java.awt.Color(153, 153, 153));
        txtNgayDang.setText("2022-11-06");
        txtNgayDang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayDangMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ngày cấp");

        txtNoiCap.setBackground(new java.awt.Color(153, 153, 153));
        txtNoiCap.setForeground(new java.awt.Color(51, 51, 51));
        txtNoiCap.setText("UBND Gò Vấp");
        txtNoiCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNoiCapMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nơi cấp");

        txaDiaChi.setBackground(new java.awt.Color(153, 153, 153));
        txaDiaChi.setColumns(20);
        txaDiaChi.setRows(5);
        txaDiaChi.setText("Dương Quảng Hàm, Gò Vấp, TP HCM");
        txaDiaChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txaDiaChiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txaDiaChi);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Loại dự án");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Ngày đăng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtMaDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtMaDuAn.setText("DA01");
        txtMaDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaDuAnMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("THÊM DỰ ÁN");

        txtNgayCap.setBackground(new java.awt.Color(153, 153, 153));
        txtNgayCap.setText("2022-10-22");
        txtNgayCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayCapMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Mã dự án");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Diện tích");

        txtTenDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtTenDuAn.setText("Mặt bằng Quận Gò Vấp");
        txtTenDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDuAnMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("NV phụ trách");

        txtNVPhuTrach.setBackground(new java.awt.Color(153, 153, 153));
        txtNVPhuTrach.setText("NV01");
        txtNVPhuTrach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNVPhuTrachMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                                .addGap(146, 146, 146)
                                .addComponent(btnThem)
                                .addGap(40, 40, 40)
                                .addComponent(btnHuy))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDienTich, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addComponent(txtTenDuAn))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(291, 291, 291))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNVPhuTrach)
                                                .addGap(44, 44, 44))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(244, 244, 244))
                                    .addComponent(txtNoiCap))))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(txtMaDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(58, 58, 58)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)))
                            .addGap(227, 227, 227))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNgayCap)
                                .addComponent(txtSoGiayPhep, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoaiDuAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayDang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(55, 55, 55)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(239, 239, 239)
                .addComponent(txtTenDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNVPhuTrach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoGiayPhep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLoaiDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgayDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void txtMaDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaDuAnMouseClicked
        // TODO add your handling code here:
        txtMaDuAn.setText(null);
    }//GEN-LAST:event_txtMaDuAnMouseClicked

    private void txtSoGiayPhepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoGiayPhepMouseClicked
        // TODO add your handling code here:
        txtSoGiayPhep.setText(null);
    }//GEN-LAST:event_txtSoGiayPhepMouseClicked

    private void txtLoaiDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoaiDuAnMouseClicked
        // TODO add your handling code here:
        txtLoaiDuAn.setText(null);
    }//GEN-LAST:event_txtLoaiDuAnMouseClicked

    private void txtTenDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDuAnMouseClicked
        // TODO add your handling code here:
       txtTenDuAn.setText(null);
    }//GEN-LAST:event_txtTenDuAnMouseClicked

    private void txtNgayCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayCapMouseClicked
        // TODO add your handling code here:
        txtNgayCap.setText(null);
    }//GEN-LAST:event_txtNgayCapMouseClicked

    private void txtNgayDangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayDangMouseClicked
        // TODO add your handling code here:
        txtNgayDang.setText(null);
    }//GEN-LAST:event_txtNgayDangMouseClicked

    private void txtDienTichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDienTichMouseClicked
        // TODO add your handling code here:
        txtDienTich.setText(null);
    }//GEN-LAST:event_txtDienTichMouseClicked

    private void txtNVPhuTrachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNVPhuTrachMouseClicked
        // TODO add your handling code here:
        txtNVPhuTrach.setText(null);
    }//GEN-LAST:event_txtNVPhuTrachMouseClicked

    private void txtNoiCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNoiCapMouseClicked
        // TODO add your handling code here:
        txtNoiCap.setText(null);
    }//GEN-LAST:event_txtNoiCapMouseClicked

    private void txaDiaChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txaDiaChiMouseClicked
        // TODO add your handling code here:
        txaDiaChi.setText(null);
    }//GEN-LAST:event_txaDiaChiMouseClicked

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProjectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDiaChi;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtLoaiDuAn;
    private javax.swing.JTextField txtMaDuAn;
    private javax.swing.JTextField txtNVPhuTrach;
    private javax.swing.JTextField txtNgayCap;
    private javax.swing.JTextField txtNgayDang;
    private javax.swing.JTextField txtNoiCap;
    private javax.swing.JTextField txtSoGiayPhep;
    private javax.swing.JTextField txtTenDuAn;
    // End of variables declaration//GEN-END:variables
}
