/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.QuanLyDuAnDAO;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.utils.XDate;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import com.mycompany.qlbatdongsan.utils.XImage;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author HO VAN DAT
 */
public class AddProjectFrame extends javax.swing.JFrame {

    QuanLyDuAnDAO dao = new QuanLyDuAnDAO();

    /**
     * Creates new form AddProjectFrame
     */
    public AddProjectFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
        setTitle("THÊM DỰ ÁN BẤT ĐỘNG SẢN DVPTP");
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    QuanLyDuAn getForm() {
        QuanLyDuAn da = new QuanLyDuAn();
        da.setMaDA(txtMaDA.getText());
        da.setTenDA(txtTenDa.getText());
        da.setBanGiao(txtThoiGianBanGiao.getText());
        da.setChuDauTu(txtChuDauTu.getText());
        da.setDiaChi(txaDiaChi.getText());
        da.setDonViTuVanKT(txtDonViTVKiThuat.getText());
        da.setHoanThien(txtThoiGianHoanThien.getText());
        da.setKhoiCong(txtThoiGianKhoiCong.getText());
        da.setKienTrucThietKe(txtKienTrucThietKe.getText());
        da.setLoaiHinhSP(txtLoaiHinhSanPham.getText());
        da.setMaNVPhuTrach(txtNVPhuTrach.getText());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();
        da.setNgayDang(XDate.toDate(dtf.format(now), "yyyy-MM-dd"));
        da.setPhapLy(txtPhapLy.getText());
        da.setQuyMo(txtQuyMo.getText());
        da.setSoLuongSanPham(txtSoLuongSanPham.getText());
        da.setTieuChuanBanGiao(txtTieuChuanBanGiao.getText());
        return da;
    }

    void add() {
        QuanLyDuAn da = getForm();
        try {
            dao.insert(da);
            ProjectFrame.fillTableDA();
            MsgBox.alert(this, "Thêm dự án thành công!");
            this.dispose();
        } catch (Exception e) {
            MsgBox.alert(this, "Đã có lỗi xảy ra!");
            e.printStackTrace();
        }

    }


    public void clearForm() {
        txtMaDA.setText("");
        txtChuDauTu.setText("");
        txtDienTichKhuCanHo.setText("");
        txtDienTichKhuThuongMai.setText("");
        txtDonViTVKiThuat.setText("");
        txtKienTrucThietKe.setText("");
        txtLoaiHinhSanPham.setText("");
        txtMatDo.setText("");
        txtNVPhuTrach.setText("");
        txtPhapLy.setText("");
        txtQuyMo.setText("");
        txtSoLuongSanPham.setText("");
        txtTenDa.setText("");
        txtThoiGianBanGiao.setText("");
        txtThoiGianHoanThien.setText("");
        txtThoiGianKhoiCong.setText("");
       txtTieuChuanBanGiao.setText("");
       txtTongDienTich.setText("");
       txtTongVonDauTu.setText("");
       txtTongDienTichSan.setText("");  
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtTongDienTich = new com.mycompany.qlbatdongsan.utils.TextField();
        txtMaDA = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTenDa = new com.mycompany.qlbatdongsan.utils.TextField();
        txtDienTichKhuCanHo = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTongDienTichSan = new com.mycompany.qlbatdongsan.utils.TextField();
        txtMatDo = new com.mycompany.qlbatdongsan.utils.TextField();
        txtDienTichKhuThuongMai = new com.mycompany.qlbatdongsan.utils.TextField();
        txtPhapLy = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTongVonDauTu = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTieuChuanBanGiao = new com.mycompany.qlbatdongsan.utils.TextField();
        txtKienTrucThietKe = new com.mycompany.qlbatdongsan.utils.TextField();
        txtDonViTVKiThuat = new com.mycompany.qlbatdongsan.utils.TextField();
        txtQuyMo = new com.mycompany.qlbatdongsan.utils.TextField();
        txtThoiGianKhoiCong = new com.mycompany.qlbatdongsan.utils.TextField();
        txtThoiGianHoanThien = new com.mycompany.qlbatdongsan.utils.TextField();
        txtThoiGianBanGiao = new com.mycompany.qlbatdongsan.utils.TextField();
        txtNVPhuTrach = new com.mycompany.qlbatdongsan.utils.TextField();
        txtChuDauTu = new com.mycompany.qlbatdongsan.utils.TextField();
        txtLoaiHinhSanPham = new com.mycompany.qlbatdongsan.utils.TextField();
        txtSoLuongSanPham = new com.mycompany.qlbatdongsan.utils.TextField();
        Logo = new javax.swing.JLabel();
        txaDiaChi = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnHuy = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblHuy = new javax.swing.JLabel();
        btnClear = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblClear = new javax.swing.JLabel();
        btnHoanTat = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblHoanTat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTongDienTich.setBackground(new java.awt.Color(255, 255, 255));
        txtTongDienTich.setForeground(new java.awt.Color(0, 0, 0));
        txtTongDienTich.setLabelText("Tổng diện tích");
        txtTongDienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongDienTichActionPerformed(evt);
            }
        });
        getContentPane().add(txtTongDienTich, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 383, 40));

        txtMaDA.setBackground(new java.awt.Color(255, 255, 255));
        txtMaDA.setForeground(new java.awt.Color(0, 0, 0));
        txtMaDA.setLabelText("Mã dự án");
        txtMaDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDAActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 383, 40));

        txtTenDa.setBackground(new java.awt.Color(255, 255, 255));
        txtTenDa.setForeground(new java.awt.Color(0, 0, 0));
        txtTenDa.setLabelText("Tên dự án");
        txtTenDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenDa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 383, 40));

        txtDienTichKhuCanHo.setBackground(new java.awt.Color(255, 255, 255));
        txtDienTichKhuCanHo.setForeground(new java.awt.Color(0, 0, 0));
        txtDienTichKhuCanHo.setLabelText("Diện tích khu căn hộ");
        txtDienTichKhuCanHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienTichKhuCanHoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDienTichKhuCanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 383, 40));

        txtTongDienTichSan.setBackground(new java.awt.Color(255, 255, 255));
        txtTongDienTichSan.setForeground(new java.awt.Color(0, 0, 0));
        txtTongDienTichSan.setLabelText("Tổng diện tích sàn");
        txtTongDienTichSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongDienTichSanActionPerformed(evt);
            }
        });
        getContentPane().add(txtTongDienTichSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 383, 40));

        txtMatDo.setBackground(new java.awt.Color(255, 255, 255));
        txtMatDo.setForeground(new java.awt.Color(0, 0, 0));
        txtMatDo.setLabelText("Mật độ");
        txtMatDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatDoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 383, 40));

        txtDienTichKhuThuongMai.setBackground(new java.awt.Color(255, 255, 255));
        txtDienTichKhuThuongMai.setForeground(new java.awt.Color(0, 0, 0));
        txtDienTichKhuThuongMai.setLabelText("Diện tích khu thương mại");
        txtDienTichKhuThuongMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienTichKhuThuongMaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtDienTichKhuThuongMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 383, 40));

        txtPhapLy.setBackground(new java.awt.Color(255, 255, 255));
        txtPhapLy.setForeground(new java.awt.Color(0, 0, 0));
        txtPhapLy.setLabelText("Pháp lý");
        txtPhapLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhapLyActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhapLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 383, 40));

        txtTongVonDauTu.setBackground(new java.awt.Color(255, 255, 255));
        txtTongVonDauTu.setForeground(new java.awt.Color(0, 0, 0));
        txtTongVonDauTu.setLabelText("Tổng vốn đầu tư");
        txtTongVonDauTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongVonDauTuActionPerformed(evt);
            }
        });
        getContentPane().add(txtTongVonDauTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 383, 40));

        txtTieuChuanBanGiao.setBackground(new java.awt.Color(255, 255, 255));
        txtTieuChuanBanGiao.setForeground(new java.awt.Color(0, 0, 0));
        txtTieuChuanBanGiao.setLabelText("Tiêu chuẩn bàn giao");
        txtTieuChuanBanGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTieuChuanBanGiaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTieuChuanBanGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 383, 40));

        txtKienTrucThietKe.setBackground(new java.awt.Color(255, 255, 255));
        txtKienTrucThietKe.setForeground(new java.awt.Color(0, 0, 0));
        txtKienTrucThietKe.setLabelText("Kiến trúc thiết kế");
        txtKienTrucThietKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKienTrucThietKeActionPerformed(evt);
            }
        });
        getContentPane().add(txtKienTrucThietKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 383, 40));

        txtDonViTVKiThuat.setBackground(new java.awt.Color(255, 255, 255));
        txtDonViTVKiThuat.setForeground(new java.awt.Color(0, 0, 0));
        txtDonViTVKiThuat.setLabelText("Đơn vị tư vấn kĩ thuật");
        txtDonViTVKiThuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonViTVKiThuatActionPerformed(evt);
            }
        });
        getContentPane().add(txtDonViTVKiThuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 383, 40));

        txtQuyMo.setBackground(new java.awt.Color(255, 255, 255));
        txtQuyMo.setForeground(new java.awt.Color(0, 0, 0));
        txtQuyMo.setLabelText("Quy mô");
        txtQuyMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuyMoActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuyMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 383, 40));

        txtThoiGianKhoiCong.setBackground(new java.awt.Color(255, 255, 255));
        txtThoiGianKhoiCong.setForeground(new java.awt.Color(0, 0, 0));
        txtThoiGianKhoiCong.setLabelText("Thời gian khởi công");
        txtThoiGianKhoiCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianKhoiCongActionPerformed(evt);
            }
        });
        getContentPane().add(txtThoiGianKhoiCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 383, 40));

        txtThoiGianHoanThien.setBackground(new java.awt.Color(255, 255, 255));
        txtThoiGianHoanThien.setForeground(new java.awt.Color(0, 0, 0));
        txtThoiGianHoanThien.setLabelText("Thời gian hoàn thiện");
        txtThoiGianHoanThien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianHoanThienActionPerformed(evt);
            }
        });
        getContentPane().add(txtThoiGianHoanThien, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 383, 40));

        txtThoiGianBanGiao.setBackground(new java.awt.Color(255, 255, 255));
        txtThoiGianBanGiao.setForeground(new java.awt.Color(0, 0, 0));
        txtThoiGianBanGiao.setLabelText("Thời gian bàn giao");
        txtThoiGianBanGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianBanGiaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtThoiGianBanGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 383, 40));

        txtNVPhuTrach.setBackground(new java.awt.Color(255, 255, 255));
        txtNVPhuTrach.setForeground(new java.awt.Color(0, 0, 0));
        txtNVPhuTrach.setLabelText("Mã nhân viên phụ trách");
        txtNVPhuTrach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNVPhuTrachActionPerformed(evt);
            }
        });
        getContentPane().add(txtNVPhuTrach, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 383, 40));

        txtChuDauTu.setBackground(new java.awt.Color(255, 255, 255));
        txtChuDauTu.setForeground(new java.awt.Color(0, 0, 0));
        txtChuDauTu.setLabelText("Chủ đầu tư");
        txtChuDauTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChuDauTuActionPerformed(evt);
            }
        });
        getContentPane().add(txtChuDauTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 383, 40));

        txtLoaiHinhSanPham.setBackground(new java.awt.Color(255, 255, 255));
        txtLoaiHinhSanPham.setForeground(new java.awt.Color(0, 0, 0));
        txtLoaiHinhSanPham.setLabelText("Loại hình sản phẩm");
        txtLoaiHinhSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiHinhSanPhamActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoaiHinhSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 383, 40));

        txtSoLuongSanPham.setBackground(new java.awt.Color(255, 255, 255));
        txtSoLuongSanPham.setForeground(new java.awt.Color(0, 0, 0));
        txtSoLuongSanPham.setLabelText("Số lượng sản phẩm");
        txtSoLuongSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongSanPhamActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoLuongSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 383, 40));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/skyebloom.png"))); // NOI18N
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 94, 357, 349));

        txaDiaChi.setBackground(new java.awt.Color(255, 255, 255));
        txaDiaChi.setColumns(20);
        txaDiaChi.setForeground(new java.awt.Color(51, 51, 51));
        txaDiaChi.setRows(5);
        txaDiaChi.setText("Dương Quảng Hàm, Gò Vấp, TP HCM");
        txaDiaChi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Địa chỉ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        txaDiaChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txaDiaChiMouseClicked(evt);
            }
        });
        getContentPane().add(txaDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 383, 77));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setRoundBottonLeft(40);
        btnHuy.setRoundBottonRight(40);
        btnHuy.setRoundTopLeft(40);
        btnHuy.setRoundTopRight(40);

        lblHuy.setBackground(new java.awt.Color(51, 51, 51));
        lblHuy.setForeground(new java.awt.Color(0, 0, 0));
        lblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-close-30.png"))); // NOI18N
        lblHuy.setText("  Hủy ");
        lblHuy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHuyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHuyLayout = new javax.swing.GroupLayout(btnHuy);
        btnHuy.setLayout(btnHuyLayout);
        btnHuyLayout.setHorizontalGroup(
            btnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnHuyLayout.setVerticalGroup(
            btnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHuyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setRoundBottonLeft(40);
        btnClear.setRoundBottonRight(40);
        btnClear.setRoundTopLeft(40);
        btnClear.setRoundTopRight(40);

        lblClear.setBackground(new java.awt.Color(51, 51, 51));
        lblClear.setForeground(new java.awt.Color(0, 0, 0));
        lblClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-clear-symbol-30.png"))); // NOI18N
        lblClear.setText("  Xóa ");
        lblClear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnClearLayout = new javax.swing.GroupLayout(btnClear);
        btnClear.setLayout(btnClearLayout);
        btnClearLayout.setHorizontalGroup(
            btnClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClear, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnClearLayout.setVerticalGroup(
            btnClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClear, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHoanTat.setBackground(new java.awt.Color(204, 204, 204));
        btnHoanTat.setRoundBottonLeft(40);
        btnHoanTat.setRoundBottonRight(40);
        btnHoanTat.setRoundTopLeft(40);
        btnHoanTat.setRoundTopRight(40);

        lblHoanTat.setBackground(new java.awt.Color(51, 51, 51));
        lblHoanTat.setForeground(new java.awt.Color(0, 0, 0));
        lblHoanTat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoanTat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-favorite-database-24.png"))); // NOI18N
        lblHoanTat.setText("Hoàn tất");
        lblHoanTat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblHoanTat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoanTatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHoanTatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHoanTatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHoanTatLayout = new javax.swing.GroupLayout(btnHoanTat);
        btnHoanTat.setLayout(btnHoanTatLayout);
        btnHoanTatLayout.setHorizontalGroup(
            btnHoanTatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoanTat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnHoanTatLayout.setVerticalGroup(
            btnHoanTatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHoanTatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHoanTat, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("THÊM DỰ ÁN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(btnHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(451, 451, 451))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txaDiaChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txaDiaChiMouseClicked
        // TODO add your handling code here:
        txaDiaChi.setText(null);
    }//GEN-LAST:event_txaDiaChiMouseClicked

    private void txtTongDienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongDienTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongDienTichActionPerformed

    private void txtMaDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDAActionPerformed

    private void txtTongDienTichSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongDienTichSanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongDienTichSanActionPerformed

    private void txtTenDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDaActionPerformed

    private void txtDienTichKhuCanHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienTichKhuCanHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienTichKhuCanHoActionPerformed

    private void txtMatDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatDoActionPerformed

    private void txtDienTichKhuThuongMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienTichKhuThuongMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienTichKhuThuongMaiActionPerformed

    private void txtPhapLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhapLyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhapLyActionPerformed

    private void txtTongVonDauTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongVonDauTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongVonDauTuActionPerformed

    private void txtTieuChuanBanGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTieuChuanBanGiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTieuChuanBanGiaoActionPerformed

    private void txtKienTrucThietKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKienTrucThietKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKienTrucThietKeActionPerformed

    private void txtDonViTVKiThuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonViTVKiThuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonViTVKiThuatActionPerformed

    private void txtQuyMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuyMoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuyMoActionPerformed

    private void txtThoiGianKhoiCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianKhoiCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiGianKhoiCongActionPerformed

    private void txtThoiGianHoanThienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianHoanThienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiGianHoanThienActionPerformed

    private void txtThoiGianBanGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianBanGiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiGianBanGiaoActionPerformed

    private void txtNVPhuTrachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNVPhuTrachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNVPhuTrachActionPerformed

    private void txtChuDauTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuDauTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChuDauTuActionPerformed

    private void txtLoaiHinhSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiHinhSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiHinhSanPhamActionPerformed

    private void txtSoLuongSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongSanPhamActionPerformed

    private void lblHoanTatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanTatMouseExited
        // TODO add your handling code here:

        btnHoanTat.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblHoanTatMouseExited

    private void lblHoanTatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanTatMouseEntered
        // TODO add your handling code here:
        btnHoanTat.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblHoanTatMouseEntered

    private void lblHoanTatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanTatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHoanTatMouseClicked

    private void lblClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseExited
        // TODO add your handling code here:
        btnClear.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblClearMouseExited

    private void lblClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseEntered
        // TODO add your handling code here:
        btnClear.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblClearMouseEntered

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_lblClearMouseClicked

    private void lblHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyMouseExited
        // TODO add your handling code here:
        btnHuy.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblHuyMouseExited

    private void lblHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyMouseEntered
        // TODO add your handling code here:
        btnHuy.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblHuyMouseEntered

    private void lblHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyMouseClicked
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn muốn hủy ?")) {
            this.dispose();
        }
    }//GEN-LAST:event_lblHuyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProjectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnClear;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnHoanTat;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblHoanTat;
    private javax.swing.JLabel lblHuy;
    private javax.swing.JTextArea txaDiaChi;
    private com.mycompany.qlbatdongsan.utils.TextField txtChuDauTu;
    private com.mycompany.qlbatdongsan.utils.TextField txtDienTichKhuCanHo;
    private com.mycompany.qlbatdongsan.utils.TextField txtDienTichKhuThuongMai;
    private com.mycompany.qlbatdongsan.utils.TextField txtDonViTVKiThuat;
    private com.mycompany.qlbatdongsan.utils.TextField txtKienTrucThietKe;
    private com.mycompany.qlbatdongsan.utils.TextField txtLoaiHinhSanPham;
    private com.mycompany.qlbatdongsan.utils.TextField txtMaDA;
    private com.mycompany.qlbatdongsan.utils.TextField txtMatDo;
    private com.mycompany.qlbatdongsan.utils.TextField txtNVPhuTrach;
    private com.mycompany.qlbatdongsan.utils.TextField txtPhapLy;
    private com.mycompany.qlbatdongsan.utils.TextField txtQuyMo;
    private com.mycompany.qlbatdongsan.utils.TextField txtSoLuongSanPham;
    private com.mycompany.qlbatdongsan.utils.TextField txtTenDa;
    private com.mycompany.qlbatdongsan.utils.TextField txtThoiGianBanGiao;
    private com.mycompany.qlbatdongsan.utils.TextField txtThoiGianHoanThien;
    private com.mycompany.qlbatdongsan.utils.TextField txtThoiGianKhoiCong;
    private com.mycompany.qlbatdongsan.utils.TextField txtTieuChuanBanGiao;
    private com.mycompany.qlbatdongsan.utils.TextField txtTongDienTich;
    private com.mycompany.qlbatdongsan.utils.TextField txtTongDienTichSan;
    private com.mycompany.qlbatdongsan.utils.TextField txtTongVonDauTu;
    // End of variables declaration//GEN-END:variables
}
