/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.SanPhamDuAnDAO;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import com.mycompany.qlbatdongsan.Entity.SanPhamDuAn;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.utils.XDate;
import java.awt.Color;

/**
 *
 * @author HO VAN DAT
 */
public class AddSPProjectFrame extends javax.swing.JFrame {
    QuanLyDuAn da;
    SanPhamDuAnDAO daoSPDA = new SanPhamDuAnDAO();
    /**
     * Creates new form AddSPProjectFrame
     */
    public AddSPProjectFrame(QuanLyDuAn entity) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.da=entity;
    }
    public SanPhamDuAn getForm(){
        SanPhamDuAn spDA = new SanPhamDuAn();  
        spDA.setMaSPDA(txtMaSPDA.getText());
        spDA.setMaDA(da.getMaDA());
        spDA.setChuSoHuu(txtChuSoHuu.getText());
        spDA.setDienTich(Double.parseDouble(txtDienTich.getText()));
        spDA.setDonViPhanPhoi(Integer.parseInt(txtDonViPhanPhoi.getText()));
        spDA.setGia(Double.parseDouble(txtGia.getText()));
        spDA.setLoaiSP(txtLoaiSP.getText());
        spDA.setPhongNgu(Integer.parseInt(txtSlPhongNgu.getText()));
        spDA.setPhongBepKhach(Integer.parseInt(txtSLPhongKhachVaBep.getText()));
        spDA.setSoTang(Integer.parseInt(txtSoTang.getText()));
        spDA.setTenSP(txtTenSP.getText());
        spDA.setTgSoHuu(txtTGSuHuu.getText());
        spDA.setThuocTang(Integer.parseInt(txtThuocTang.getText()));
        spDA.setTienNghi(txtTienNghi.getText());
        spDA.setToa(txtToa.getText());
        spDA.setTrangThai(txtTrangThai.getText());
        spDA.setWC(Integer.parseInt(txtPhongWC.getText()));
        return spDA;
    }
    
    void add() {
        SanPhamDuAn da = getForm();
        try {
            daoSPDA.insert(da);         
            MsgBox.alert(this, "Thêm  sản phẩm dự án thành công!");
            ManagerProjectPanel.initForm();
            this.dispose();
        } catch (Exception e) {
            MsgBox.alert(this, "Đã có lỗi xảy ra!");
            e.printStackTrace();
        }

    }
    void clearForm(){
       txtChuSoHuu.setText("");
       txtDienTich.setText("");
       txtDonViPhanPhoi.setText("");
       txtGia.setText("");
       txtLoaiSP.setText("");
       txtMaSPDA.setText("");
       txtPhongWC.setText("");
       txtSLPhongKhachVaBep.setText("");
       txtSlPhongNgu.setText("");
       txtSoTang.setText("");
       txtTGSuHuu.setText("");
       txtTenSP.setText("");
       txtThuocTang.setText("");
       txtTienNghi.setText("");
       txtToa.setText("");
       txtTrangThai.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaSPDA = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTenSP = new com.mycompany.qlbatdongsan.utils.TextField();
        txtDienTich = new com.mycompany.qlbatdongsan.utils.TextField();
        txtSLPhongKhachVaBep = new com.mycompany.qlbatdongsan.utils.TextField();
        txtSlPhongNgu = new com.mycompany.qlbatdongsan.utils.TextField();
        txtPhongWC = new com.mycompany.qlbatdongsan.utils.TextField();
        txtGia = new com.mycompany.qlbatdongsan.utils.TextField();
        txtLoaiSP = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTrangThai = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTienNghi = new com.mycompany.qlbatdongsan.utils.TextField();
        txtChuSoHuu = new com.mycompany.qlbatdongsan.utils.TextField();
        txtTGSuHuu = new com.mycompany.qlbatdongsan.utils.TextField();
        txtSoTang = new com.mycompany.qlbatdongsan.utils.TextField();
        txtThuocTang = new com.mycompany.qlbatdongsan.utils.TextField();
        txtDonViPhanPhoi = new com.mycompany.qlbatdongsan.utils.TextField();
        txtToa = new com.mycompany.qlbatdongsan.utils.TextField();
        btnClear = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblClear = new javax.swing.JLabel();
        btnHuy = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblHuy = new javax.swing.JLabel();
        btnHoanTat = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblHoanTat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("THÊM SẢN PHẨM DỰ ÁN");

        txtMaSPDA.setLabelText("Mã sản phẩm");

        txtTenSP.setLabelText("Tên sản phẩm");

        txtDienTich.setLabelText("Diện tích");

        txtSLPhongKhachVaBep.setToolTipText("");
        txtSLPhongKhachVaBep.setLabelText("SL Phòng Bếp và Phòng Khách");

        txtSlPhongNgu.setLabelText("SL Phòng Ngủ");

        txtPhongWC.setLabelText("Sl Phòng WC");
        txtPhongWC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhongWCActionPerformed(evt);
            }
        });

        txtGia.setLabelText("Giá");

        txtLoaiSP.setLabelText("Loại sản phẩm");

        txtTrangThai.setLabelText("Trạng thái");

        txtTienNghi.setLabelText("Tiện nghi");

        txtChuSoHuu.setLabelText("Chủ sở hữu");

        txtTGSuHuu.setLabelText("Thời gian sở hũu");

        txtSoTang.setLabelText("Số tầng");

        txtThuocTang.setLabelText("Thuộc tầng");

        txtDonViPhanPhoi.setLabelText("Đơn vị phân phối");

        txtToa.setLabelText("Tòa");

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setRoundBottonLeft(40);
        btnClear.setRoundBottonRight(40);
        btnClear.setRoundTopLeft(40);
        btnClear.setRoundTopRight(40);

        lblClear.setBackground(new java.awt.Color(51, 51, 51));
        lblClear.setForeground(new java.awt.Color(0, 0, 0));
        lblClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-clear-symbol-30.png"))); // NOI18N
        lblClear.setText("  Xóa ");
        lblClear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnClearLayout = new javax.swing.GroupLayout(btnClear);
        btnClear.setLayout(btnClearLayout);
        btnClearLayout.setHorizontalGroup(
            btnClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClear, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnClearLayout.setVerticalGroup(
            btnClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setRoundBottonLeft(40);
        btnHuy.setRoundBottonRight(40);
        btnHuy.setRoundTopLeft(40);
        btnHuy.setRoundTopRight(40);

        lblHuy.setBackground(new java.awt.Color(51, 51, 51));
        lblHuy.setForeground(new java.awt.Color(0, 0, 0));
        lblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-close-30.png"))); // NOI18N
        lblHuy.setText("Hủy");
        lblHuy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHuyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHuyLayout = new javax.swing.GroupLayout(btnHuy);
        btnHuy.setLayout(btnHuyLayout);
        btnHuyLayout.setHorizontalGroup(
            btnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnHuyLayout.setVerticalGroup(
            btnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHuyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHoanTat.setBackground(new java.awt.Color(204, 204, 204));
        btnHoanTat.setRoundBottonLeft(40);
        btnHoanTat.setRoundBottonRight(40);
        btnHoanTat.setRoundTopLeft(40);
        btnHoanTat.setRoundTopRight(40);

        lblHoanTat.setBackground(new java.awt.Color(51, 51, 51));
        lblHoanTat.setForeground(new java.awt.Color(0, 0, 0));
        lblHoanTat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoanTat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-favorite-database-24.png"))); // NOI18N
        lblHoanTat.setText("Hoàn tất");
        lblHoanTat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblHoanTat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoanTatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHoanTatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHoanTatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHoanTatLayout = new javax.swing.GroupLayout(btnHoanTat);
        btnHoanTat.setLayout(btnHoanTatLayout);
        btnHoanTatLayout.setHorizontalGroup(
            btnHoanTatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoanTat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnHoanTatLayout.setVerticalGroup(
            btnHoanTatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHoanTatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHoanTat, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSPDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDienTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSLPhongKhachVaBep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSlPhongNgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhongWC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLoaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDonViPhanPhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtThuocTang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoTang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTGSuHuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtChuSoHuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTienNghi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSPDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChuSoHuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSLPhongKhachVaBep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTGSuHuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSlPhongNgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhongWC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThuocTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonViPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_lblClearMouseClicked

    private void lblClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseEntered
        // TODO add your handling code here:
        btnClear.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblClearMouseEntered

    private void lblClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseExited
        // TODO add your handling code here:
        btnClear.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblClearMouseExited

    private void lblHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblHuyMouseClicked

    private void lblHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyMouseEntered
        // TODO add your handling code here:
        btnHuy.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblHuyMouseEntered

    private void lblHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyMouseExited
        // TODO add your handling code here:
        btnHuy.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblHuyMouseExited

    private void lblHoanTatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanTatMouseClicked
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_lblHoanTatMouseClicked

    private void lblHoanTatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanTatMouseEntered
        // TODO add your handling code here:
        btnHoanTat.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblHoanTatMouseEntered

    private void lblHoanTatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanTatMouseExited
        // TODO add your handling code here:
        btnHoanTat.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblHoanTatMouseExited

    private void txtPhongWCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhongWCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhongWCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlbatdongsan.utils.PanelRound btnClear;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnHoanTat;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblHoanTat;
    private javax.swing.JLabel lblHuy;
    private com.mycompany.qlbatdongsan.utils.TextField txtChuSoHuu;
    private com.mycompany.qlbatdongsan.utils.TextField txtDienTich;
    private com.mycompany.qlbatdongsan.utils.TextField txtDonViPhanPhoi;
    private com.mycompany.qlbatdongsan.utils.TextField txtGia;
    private com.mycompany.qlbatdongsan.utils.TextField txtLoaiSP;
    private com.mycompany.qlbatdongsan.utils.TextField txtMaSPDA;
    private com.mycompany.qlbatdongsan.utils.TextField txtPhongWC;
    private com.mycompany.qlbatdongsan.utils.TextField txtSLPhongKhachVaBep;
    private com.mycompany.qlbatdongsan.utils.TextField txtSlPhongNgu;
    private com.mycompany.qlbatdongsan.utils.TextField txtSoTang;
    private com.mycompany.qlbatdongsan.utils.TextField txtTGSuHuu;
    private com.mycompany.qlbatdongsan.utils.TextField txtTenSP;
    private com.mycompany.qlbatdongsan.utils.TextField txtThuocTang;
    private com.mycompany.qlbatdongsan.utils.TextField txtTienNghi;
    private com.mycompany.qlbatdongsan.utils.TextField txtToa;
    private com.mycompany.qlbatdongsan.utils.TextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
