/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.TaiLieuDuAnDAO;
import com.mycompany.qlbatdongsan.Entity.SanPhamDuAn;
import com.mycompany.qlbatdongsan.Entity.TaiLieuDuAN;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.utils.XDate;
import com.mycompany.qlbatdongsan.utils.XImage;
import java.awt.Image;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author HO VAN DAT
 */
public class EditSPProjectFrame extends javax.swing.JFrame {
    SanPhamDuAn spda;
    JFileChooser jFileChooser = new JFileChooser();
    TaiLieuDuAnDAO daoImage = new TaiLieuDuAnDAO();
    private int indexImage;

    public EditSPProjectFrame(SanPhamDuAn entity) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.spda = entity;
        SeeImageProject();
        setForm(spda);
        indexImage = ImageProject().size() - 1;
    }
     public List<TaiLieuDuAN> ImageProject() {
        List<TaiLieuDuAN> list = daoImage.selectByIdmaSPDA(spda.getMaSPDA());
        return list;
    }

    public void SeeImageProject() {
        for (int i = 0; i < ImageProject().size(); i++) {
            if (i == indexImage) {
                lblImageDa.setIcon(new ImageIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\imgAvartar\\" + ImageProject().get(i).getHinh()).getImage().getScaledInstance(lblImageDa.getWidth(), lblImageDa.getHeight(), Image.SCALE_DEFAULT)));
            }
        }
    }

    public void Next() {
        if (indexImage == ImageProject().size() - 1) {
            indexImage = 0;
        } else {
            indexImage++;
        }
        SeeImageProject();
    }

    public void Previous() {
        if (indexImage == 0) {
            indexImage = ImageProject().size() - 1;
        } else {
            indexImage++;
        }
        SeeImageProject();
    }

    public void setForm(SanPhamDuAn da) {
//        txtMaDuAn.setText(da.getMaDA());
//        txtTenDuAn.setText(da.getTenDA());
//        txaDiaChi.setText(da.getDiaChi());
//        txtDienTich.setText(Float.toString(da.getDienTich()));
//        txtSoGiayPhep.setText(Float.toString(da.getSoGiayPhep()));
//        txtNgayCap.setText(String.valueOf(da.getNgayCap()));
//        txtNoiCap.setText(da.getNoiCap());
//        txtNVPhuTrach.setText(da.getMaNVPhuTrach());
//        txtNgayDang.setText(String.valueOf(da.getNgayDang()));
//        txtLoaiDuAn.setText(da.getLoaiDA());
//        txtMaSPDuAn.setText(da.getMaSPDA());
//        txtTrangThai.setText(da.getTrangThai());
//        txtMaSanGiaoDich.setText(String.valueOf(da.getMaSGD()));
    }

    public void addImage(File file) {
        TaiLieuDuAN image = new TaiLieuDuAN();
//        image.setTenTaiLieu("Hình sản phẩm: " + spda.getTenDA());
        image.setDienGiai("Hình sản phẩm");
        image.setHinh(file.getName());
        image.setMaDA(null);
        image.setMaSPDA(spda.getMaSPDA());
        image.setMaKH(null);
//        image.setNhanVien(spda.getMaNVPhuTrach());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();
        image.setNgayCapNhat(XDate.toDate(dtf.format(now), "yyyy-MM-dd"));
        try {
            daoImage.insert(image);
            ImageProject();
            indexImage = ImageProject().size() - 1;
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi lưu hình ảnh");
            e.printStackTrace();
        }
    }

    public void chonAnh() {
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            XImage.save(file);
            ImageIcon icon = XImage.read(file.getName());
            lblImageDa.setIcon(icon);
            lblImageDa.setToolTipText(file.getName());
            addImage(file);
        }
    }
    
    public void RemoveImage(){
        if (MsgBox.confirm(this, "Bạn có chắc chắn muốn xóa bức hình này!")) {
            try {
                 daoImage.delete(ImageProject().get(indexImage).getKyHieu());
                 MsgBox.alert(this, "Xóa thành công hình ảnh!");
            } catch (Exception e) {
                MsgBox.alert(this, "Lỗi khi xóa hình ảnh");
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenDuAn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDienTich = new javax.swing.JTextField();
        txtNVPhuTrach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoGiayPhep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblImageDa = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnNext = new javax.swing.JLabel();
        txtLoaiDuAn = new javax.swing.JTextField();
        btnPrevious = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMaDuAn = new javax.swing.JTextField();
        btnXoaImage = new javax.swing.JButton();
        txtNgayDang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayCap = new javax.swing.JTextField();
        txtNoiCap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDiaChi = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtMaSPDuAn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtMaSanGiaoDich = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTenDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtTenDuAn.setText("Mặt bằng Quận Gò Vấp");
        txtTenDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDuAnMouseClicked(evt);
            }
        });
        txtTenDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDuAnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("NV phụ trách");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Loại dự án");

        txtDienTich.setBackground(new java.awt.Color(153, 153, 153));
        txtDienTich.setText("700");
        txtDienTich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDienTichMouseClicked(evt);
            }
        });

        txtNVPhuTrach.setBackground(new java.awt.Color(153, 153, 153));
        txtNVPhuTrach.setText("NV01");
        txtNVPhuTrach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNVPhuTrachMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tên sản phẩm");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Ngày đăng");

        txtSoGiayPhep.setBackground(new java.awt.Color(153, 153, 153));
        txtSoGiayPhep.setText("1412");
        txtSoGiayPhep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoGiayPhepMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Hình ảnh");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Địa chỉ");

        lblImageDa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageDa.setText("Hình ảnh");
        lblImageDa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setText("Thêm hình");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-next-page-64.png"))); // NOI18N
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });

        txtLoaiDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtLoaiDuAn.setForeground(new java.awt.Color(51, 51, 51));
        txtLoaiDuAn.setText("Đất nền");
        txtLoaiDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoaiDuAnMouseClicked(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-back-to-64.png"))); // NOI18N
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPreviousMouseExited(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });

        btnThem1.setText("Xong");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Số giấy phép");

        txtMaDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtMaDuAn.setText("DA01");
        txtMaDuAn.setEnabled(false);
        txtMaDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaDuAnMouseClicked(evt);
            }
        });

        btnXoaImage.setText("Xóa hình");
        btnXoaImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaImageActionPerformed(evt);
            }
        });

        txtNgayDang.setBackground(new java.awt.Color(153, 153, 153));
        txtNgayDang.setText("2022-11-06");
        txtNgayDang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayDangMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CHỈNH SỬA SẢN PHẨM");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ngày cấp");

        txtNgayCap.setBackground(new java.awt.Color(153, 153, 153));
        txtNgayCap.setText("2022-10-22");
        txtNgayCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayCapMouseClicked(evt);
            }
        });

        txtNoiCap.setBackground(new java.awt.Color(153, 153, 153));
        txtNoiCap.setText("UBND Gò Vấp");
        txtNoiCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNoiCapMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Mã dự án");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nơi cấp");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Diện tích");

        txaDiaChi.setBackground(new java.awt.Color(153, 153, 153));
        txaDiaChi.setColumns(20);
        txaDiaChi.setRows(5);
        txaDiaChi.setText("Dương Quảng Hàm, Gò Vấp, TP HCM");
        txaDiaChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txaDiaChiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txaDiaChi);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Mã sản phẩm dự án");

        txtMaSPDuAn.setBackground(new java.awt.Color(153, 153, 153));
        txtMaSPDuAn.setText("SPDA01");
        txtMaSPDuAn.setEnabled(false);
        txtMaSPDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaSPDuAnMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Trạng thái");

        txtTrangThai.setBackground(new java.awt.Color(153, 153, 153));
        txtTrangThai.setText("Mở bán");
        txtTrangThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTrangThaiMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Mã sàn giao dịch");

        txtMaSanGiaoDich.setBackground(new java.awt.Color(153, 153, 153));
        txtMaSanGiaoDich.setText("121");
        txtMaSanGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaSanGiaoDichMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHuy)
                                .addGap(18, 18, 18)
                                .addComponent(btnThem1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(txtMaDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel3)
                                            .addComponent(txtTenDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel13)
                                    .addComponent(txtMaSPDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNgayCap, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSoGiayPhep, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgayDang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                                    .addComponent(jLabel9)
                                    .addComponent(txtNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(txtLoaiDuAn, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtNVPhuTrach)
                                    .addComponent(jLabel14)
                                    .addComponent(txtTrangThai)
                                    .addComponent(jLabel15)
                                    .addComponent(txtMaSanGiaoDich))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblImageDa, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnXoaImage)
                                                .addGap(32, 32, 32)
                                                .addComponent(btnThem))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoaiDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNVPhuTrach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSPDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoGiayPhep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(lblImageDa, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(232, 232, 232))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDuAnMouseClicked
        // TODO add your handling code here:
        txtTenDuAn.setText(null);
    }//GEN-LAST:event_txtTenDuAnMouseClicked

    private void txtDienTichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDienTichMouseClicked
        // TODO add your handling code here:
        txtDienTich.setText(null);
    }//GEN-LAST:event_txtDienTichMouseClicked

    private void txtNVPhuTrachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNVPhuTrachMouseClicked
        // TODO add your handling code here:
        txtNVPhuTrach.setText(null);
    }//GEN-LAST:event_txtNVPhuTrachMouseClicked

    private void txtSoGiayPhepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoGiayPhepMouseClicked
        // TODO add your handling code here:
        txtSoGiayPhep.setText(null);
    }//GEN-LAST:event_txtSoGiayPhepMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-circled-right-64.png"));
        Next();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-1-64.png"));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-64.png"));
    }//GEN-LAST:event_btnNextMouseExited

    private void txtLoaiDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoaiDuAnMouseClicked
        // TODO add your handling code here:
        txtLoaiDuAn.setText(null);
    }//GEN-LAST:event_txtLoaiDuAnMouseClicked

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code her
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-go-back-64.png"));
        Previous();
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void btnPreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseEntered
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-1-64.png"));
    }//GEN-LAST:event_btnPreviousMouseEntered

    private void btnPreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseExited
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-64.png"));
    }//GEN-LAST:event_btnPreviousMouseExited

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void txtMaDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaDuAnMouseClicked
        // TODO add your handling code here:
        txtMaDuAn.setText(null);
    }//GEN-LAST:event_txtMaDuAnMouseClicked

    private void btnXoaImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaImageActionPerformed
        // TODO add your handling code here:
        RemoveImage();
        ImageProject();
        indexImage = ImageProject().size()-1;
        SeeImageProject();
    }//GEN-LAST:event_btnXoaImageActionPerformed

    private void txtNgayDangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayDangMouseClicked
        // TODO add your handling code here:
        txtNgayDang.setText(null);
    }//GEN-LAST:event_txtNgayDangMouseClicked

    private void txtNgayCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayCapMouseClicked
        // TODO add your handling code here:
        txtNgayCap.setText(null);
    }//GEN-LAST:event_txtNgayCapMouseClicked

    private void txtNoiCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNoiCapMouseClicked
        // TODO add your handling code here:
        txtNoiCap.setText(null);
    }//GEN-LAST:event_txtNoiCapMouseClicked

    private void txaDiaChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txaDiaChiMouseClicked
        // TODO add your handling code here:
        txaDiaChi.setText(null);
    }//GEN-LAST:event_txaDiaChiMouseClicked

    private void txtTenDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDuAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDuAnActionPerformed

    private void txtMaSPDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaSPDuAnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPDuAnMouseClicked

    private void txtTrangThaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTrangThaiMouseClicked
        // TODO add your handling code here:
        txtTrangThai.setText(null);
    }//GEN-LAST:event_txtTrangThaiMouseClicked

    private void txtMaSanGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaSanGiaoDichMouseClicked
        // TODO add your handling code here:
        txtMaSanGiaoDich.setText(null);
    }//GEN-LAST:event_txtMaSanGiaoDichMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSPProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrevious;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoaImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImageDa;
    private javax.swing.JTextArea txaDiaChi;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtLoaiDuAn;
    private javax.swing.JTextField txtMaDuAn;
    private javax.swing.JTextField txtMaSPDuAn;
    private javax.swing.JTextField txtMaSanGiaoDich;
    private javax.swing.JTextField txtNVPhuTrach;
    private javax.swing.JTextField txtNgayCap;
    private javax.swing.JTextField txtNgayDang;
    private javax.swing.JTextField txtNoiCap;
    private javax.swing.JTextField txtSoGiayPhep;
    private javax.swing.JTextField txtTenDuAn;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
