/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.MailDAO;
import com.mycompany.qlbatdongsan.Entity.Mails;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.utils.XDate;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HO VAN DAT
 */
public class HopThuDenPanel extends javax.swing.JPanel {

    DefaultTableModel model;
    MailDAO dao = new MailDAO();
    List<Mails> list = dao.selectByLoaiThu("Thư Đến");
    private int row = -1;

    /**
     * Creates new form HopThuDenPanel
     */
    public HopThuDenPanel() {
        initComponents();
        initTableHopThuDen();
        fillToTable();
        EmailFrame.lblSLHopThuDen.setText(String.valueOf(list.size()));
    }

    public void initTableHopThuDen() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int i, int j) {
                return false;
            }
        };
        model.setColumnCount(3);
        model.setRowCount(0);
        tblHopThuDen.setModel(model);
        
    }
    public void fillToTable() {
        tblHopThuDen.setRowHeight(30);
        tblHopThuDen.getColumnModel().getColumn(0).setMaxWidth(200);
        tblHopThuDen.getColumnModel().getColumn(1).setMaxWidth(1000);
        tblHopThuDen.getColumnModel().getColumn(2).setMaxWidth(70);
        tblHopThuDen.setTableHeader(null);
        model = (DefaultTableModel) tblHopThuDen.getModel();
        model.setRowCount(0);
        try {
            for (Mails mail : list) {
                Object[] row = {
                    mail.getEmailNguoiNhan(),
                    mail.getNoiDung(),
                    XDate.toString(mail.getThoiGian(), "yyyy-MM"),
                };
                model.addRow(row);
            }
            System.out.println("Hiện thư thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Đã xảy ra lỗi khi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblHopThuDen = new javax.swing.JTable();

        tblHopThuDen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblHopThuDen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopThuDenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHopThuDen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHopThuDenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopThuDenMouseClicked
        // TODO add your handling code here:
        this.row = tblHopThuDen.rowAtPoint(evt.getPoint());
        EmailFrame.panelTransaction1.display(new SeeMailFrame(dao.selectById(list.get(row).getMaEmail())));
    }//GEN-LAST:event_tblHopThuDenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHopThuDen;
    // End of variables declaration//GEN-END:variables
}
