
package com.mycompany.qlbatdongsan.ui;
import com.mycompany.qlbatdongsan.utils.PanelRound;
import com.mycompany.qlbatdongsan.utils.Auth;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.utils.XImage;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author HO VAN DAT
 */
public class Main extends javax.swing.JFrame {

    private int[] status = {0, 1, 0, 0, 0, 0};
    private int indexForMenuMain = 1;

    public Main() {
        initComponents();      
        ClickEffectForPanel();
//        btnNotes1.setForeground(Color.BLUE);
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-mouse-40.png")).getImage(), new Point(0, 0), "Custom cursor");
        setCursor(cursor);
        panelTransactionAllMain.display(new NotesFrame());
        init(); 
    }
    void init(){
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("HỆ THỐNG QUẢN LÝ BẤT ĐỘNG SẢN DVPTP");
        setBounds(this.getX(), this.getY()-50, this.getWidth(), this.getHeight()+100);
    }
    void ketThuc(){
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc ?")) {
            System.exit(0);
        }
    }
    void openGioiThieu(){
        new    GioiThieuJDialog(this, true).setVisible(true);
    }

    //Hover for Label
    public void HoverForLabel(JLabel label) {
        label.setForeground(Color.BLUE);
    }
    //Hover effect for ImageAvatar
    public void HoverForImageAvatarEntered(int index){
        JComponent[] comp ={lblExit,lblNontification,lblChart,lblCloud,lblFavorate,lblHomePage};
        JPanel[] Panels ={btnExit,btnNontification,btnChart,btnCloud,btnFavorate,btnHomePage};
        Panels[index].setBounds(Panels[index].getX()-5, Panels[index].getY()-5,Panels[index].getWidth()+10,  Panels[index].getHeight()+10);
        comp[index].setBounds(comp[index].getX(), comp[index].getY(),comp[index].getWidth()+10,  comp[index].getHeight()+10);         
    }
    public void HoverForImageAvatarExited(int index){
        JComponent[] comp ={lblExit,lblNontification,lblChart,lblCloud,lblFavorate,lblHomePage};
        JPanel[] Panels ={btnExit,btnNontification,btnChart,btnCloud,btnFavorate,btnHomePage};
        Panels[index].setBounds(Panels[index].getX()+5, Panels[index].getY()+5,Panels[index].getWidth()-10,  Panels[index].getHeight()-10);
        comp[index].setBounds(comp[index].getX(), comp[index].getY(),comp[index].getWidth()-10,  comp[index].getHeight()-10);         
    }
    //Exited Effect
    public void ExitedForLabel(JLabel label, int statusID) {
        if (status[statusID] == 1) {
            label.setForeground(Color.BLUE);
        } else {
            label.setForeground(new Color(153,153,153));
        }
    }
    
    // Click Effect for panel
    public void ClickEffectForPanel() {

        JPanel[] panel = {btnDashBoard, btnNotes, btnEmail, btnFiles, btnSetting, btnCalendar};
         JLabel[] label = {btnDashBoard1, btnNotes1, btnEmail1, btnFiles1, btnSetting1, btnCalendar1};
        for (int i = 0; i < 6; i++) {
            if (indexForMenuMain == i) {
                panel[i].setBackground(new Color(255, 255, 255));
                label[i].setForeground(Color.BLUE);
            } else {
                panel[i].setBackground(new Color(204,204,204));
                label[i].setForeground(new Color(153,153,153));
            }
        }
        for (int i = 0; i < status.length; i++) {
            status[i] = 0;
        }
        status[indexForMenuMain]=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pal_Head = new javax.swing.JPanel();
        btn_VeChungToi = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        btnChinhSachNguoiDung = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        btnUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblExit = new javax.swing.JLabel();
        btnNontification = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblNontification = new javax.swing.JLabel();
        panelRound4 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        panelRound1 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        txtSearchMain = new javax.swing.JTextField();
        lblNontification1 = new javax.swing.JLabel();
        lblNontification2 = new javax.swing.JLabel();
        palSettingLeft = new javax.swing.JPanel();
        btnChart = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblChart = new javax.swing.JLabel();
        btnCloud = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblCloud = new javax.swing.JLabel();
        btnFavorate = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblFavorate = new javax.swing.JLabel();
        btnHomePage = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblHomePage = new javax.swing.JLabel();
        imageAvatar1 = new com.mycompany.qlbatdongsan.utils.ImageAvatar();
        imageAvatar2 = new com.mycompany.qlbatdongsan.utils.ImageAvatar();
        imageAvatar3 = new com.mycompany.qlbatdongsan.utils.ImageAvatar();
        imageAvatar4 = new com.mycompany.qlbatdongsan.utils.ImageAvatar();
        pal_AllMain = new javax.swing.JPanel();
        lblNameUser = new javax.swing.JLabel();
        lblEmailUser = new javax.swing.JLabel();
        panelRound3 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        panelTransactionAllMain = new com.mycompany.qlbatdongsan.utils.PanelTransaction();
        panelRound9 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        imageAvatarInWork = new com.mycompany.qlbatdongsan.utils.ImageAvatar();
        palMenu = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnDashBoard = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnDashBoard1 = new javax.swing.JLabel();
        btnFiles = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnFiles1 = new javax.swing.JLabel();
        btnNotes = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnNotes1 = new javax.swing.JLabel();
        btnEmail = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnEmail1 = new javax.swing.JLabel();
        btnSetting = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnSetting1 = new javax.swing.JLabel();
        btnCalendar = new com.mycompany.qlbatdongsan.utils.PanelRound();
        btnCalendar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pal_Head.setBackground(new java.awt.Color(204, 204, 204));
        pal_Head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pal_HeadMouseClicked(evt);
            }
        });

        btn_VeChungToi.setBackground(new java.awt.Color(153, 153, 153));
        btn_VeChungToi.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_VeChungToi.setForeground(new java.awt.Color(102, 102, 102));
        btn_VeChungToi.setText("Về chúng tôi");
        btn_VeChungToi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VeChungToiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_VeChungToiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_VeChungToiMouseExited(evt);
            }
        });

        lblChucVu.setBackground(new java.awt.Color(153, 153, 153));
        lblChucVu.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(102, 102, 102));
        lblChucVu.setText("Quản lý");
        lblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChucVuMouseClicked(evt);
            }
        });

        btnChinhSachNguoiDung.setBackground(new java.awt.Color(153, 153, 153));
        btnChinhSachNguoiDung.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnChinhSachNguoiDung.setForeground(new java.awt.Color(102, 102, 102));
        btnChinhSachNguoiDung.setText("Chính sách người dùng");
        btnChinhSachNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChinhSachNguoiDungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChinhSachNguoiDungMouseExited(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(153, 153, 153));
        btnReport.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnReport.setForeground(new java.awt.Color(102, 102, 102));
        btnReport.setText("Báo lỗi");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        btnUserName.setBackground(new java.awt.Color(102, 102, 102));
        btnUserName.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnUserName.setForeground(new java.awt.Color(102, 102, 102));
        btnUserName.setText("Đạt Hồ");
        btnUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserNameMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/user-circle.256x256.png"))); // NOI18N

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setRoundBottonLeft(60);
        btnExit.setRoundBottonRight(60);
        btnExit.setRoundTopLeft(60);
        btnExit.setRoundTopRight(60);

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/times-circle.256x256.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNontification.setBackground(new java.awt.Color(255, 255, 255));
        btnNontification.setRoundBottonLeft(60);
        btnNontification.setRoundBottonRight(60);
        btnNontification.setRoundTopLeft(60);
        btnNontification.setRoundTopRight(60);

        lblNontification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNontification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/notification-solid.235x256.png"))); // NOI18N
        lblNontification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNontificationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNontificationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNontificationLayout = new javax.swing.GroupLayout(btnNontification);
        btnNontification.setLayout(btnNontificationLayout);
        btnNontificationLayout.setHorizontalGroup(
            btnNontificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNontificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNontification, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnNontificationLayout.setVerticalGroup(
            btnNontificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNontificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNontification, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottonLeft(60);
        panelRound4.setRoundBottonRight(60);
        panelRound4.setRoundTopLeft(60);
        panelRound4.setRoundTopRight(60);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/ellipsis-h.256x57.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.setRoundBottonLeft(30);
        panelRound1.setRoundBottonRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        txtSearchMain.setText("Nhập chức năng muốn tìm");
        txtSearchMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchMainActionPerformed(evt);
            }
        });

        lblNontification1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNontification1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-left-click-30.png"))); // NOI18N
        lblNontification1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNontification1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNontification1MouseExited(evt);
            }
        });

        lblNontification2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNontification2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/search.256x256.png"))); // NOI18N
        lblNontification2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNontification2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNontification2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(txtSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNontification1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblNontification2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGap(361, 361, 361)))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearchMain)
                    .addComponent(lblNontification1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNontification2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pal_HeadLayout = new javax.swing.GroupLayout(pal_Head);
        pal_Head.setLayout(pal_HeadLayout);
        pal_HeadLayout.setHorizontalGroup(
            pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_HeadLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btn_VeChungToi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReport)
                .addGap(20, 20, 20)
                .addComponent(btnChinhSachNguoiDung)
                .addGap(138, 138, 138)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnNontification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pal_HeadLayout.setVerticalGroup(
            pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_HeadLayout.createSequentialGroup()
                .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pal_HeadLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pal_HeadLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNontification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pal_HeadLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChucVu)
                            .addComponent(btn_VeChungToi)
                            .addComponent(btnReport)
                            .addComponent(btnChinhSachNguoiDung))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        palSettingLeft.setBackground(new java.awt.Color(204, 204, 204));
        palSettingLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnChart.setBackground(new java.awt.Color(255, 255, 255));
        btnChart.setRoundBottonLeft(60);
        btnChart.setRoundBottonRight(60);
        btnChart.setRoundTopLeft(60);
        btnChart.setRoundTopRight(60);

        lblChart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-financial-crisis-30.png"))); // NOI18N
        lblChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblChartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnChartLayout = new javax.swing.GroupLayout(btnChart);
        btnChart.setLayout(btnChartLayout);
        btnChartLayout.setHorizontalGroup(
            btnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnChartLayout.setVerticalGroup(
            btnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCloud.setBackground(new java.awt.Color(255, 255, 255));
        btnCloud.setRoundBottonLeft(60);
        btnCloud.setRoundBottonRight(60);
        btnCloud.setRoundTopLeft(60);
        btnCloud.setRoundTopRight(60);

        lblCloud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/cloud.256x163.png"))); // NOI18N
        lblCloud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloudMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloudLayout = new javax.swing.GroupLayout(btnCloud);
        btnCloud.setLayout(btnCloudLayout);
        btnCloudLayout.setHorizontalGroup(
            btnCloudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCloud, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCloudLayout.setVerticalGroup(
            btnCloudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCloud, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFavorate.setBackground(new java.awt.Color(255, 255, 255));
        btnFavorate.setRoundBottonLeft(60);
        btnFavorate.setRoundBottonRight(60);
        btnFavorate.setRoundTopLeft(60);
        btnFavorate.setRoundTopRight(60);

        lblFavorate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFavorate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/star.256x244.png"))); // NOI18N
        lblFavorate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFavorateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFavorateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFavorateLayout = new javax.swing.GroupLayout(btnFavorate);
        btnFavorate.setLayout(btnFavorateLayout);
        btnFavorateLayout.setHorizontalGroup(
            btnFavorateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFavorateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFavorate, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnFavorateLayout.setVerticalGroup(
            btnFavorateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFavorateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFavorate, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHomePage.setBackground(new java.awt.Color(255, 255, 255));
        btnHomePage.setRoundBottonLeft(60);
        btnHomePage.setRoundBottonRight(60);
        btnHomePage.setRoundTopLeft(60);
        btnHomePage.setRoundTopRight(60);

        lblHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/world.256x256.png"))); // NOI18N
        lblHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomePageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomePageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHomePageLayout = new javax.swing.GroupLayout(btnHomePage);
        btnHomePage.setLayout(btnHomePageLayout);
        btnHomePageLayout.setHorizontalGroup(
            btnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnHomePageLayout.setVerticalGroup(
            btnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/NgPhu.png"))); // NOI18N
        imageAvatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatar1MouseExited(evt);
            }
        });

        imageAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/ThanhVySv2.png"))); // NOI18N
        imageAvatar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatar2MouseExited(evt);
            }
        });

        imageAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/287804274_566201661558490_5683726345009216491_n.jpg"))); // NOI18N
        imageAvatar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatar3MouseExited(evt);
            }
        });

        imageAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/ThuThuy.png"))); // NOI18N
        imageAvatar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatar4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout palSettingLeftLayout = new javax.swing.GroupLayout(palSettingLeft);
        palSettingLeft.setLayout(palSettingLeftLayout);
        palSettingLeftLayout.setHorizontalGroup(
            palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palSettingLeftLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCloud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFavorate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        palSettingLeftLayout.setVerticalGroup(
            palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palSettingLeftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCloud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFavorate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pal_AllMain.setBackground(new java.awt.Color(204, 204, 204));
        pal_AllMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblNameUser.setFont(new java.awt.Font("Roboto Slab Thin", 1, 14)); // NOI18N
        lblNameUser.setForeground(new java.awt.Color(51, 51, 51));
        lblNameUser.setText("Hello Trần Thanh Vỵ");

        lblEmailUser.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        lblEmailUser.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailUser.setText("thanhvy2411@gmail.com");

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottonLeft(30);
        panelRound3.setRoundBottonRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTransactionAllMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransactionAllMain, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        panelRound9.setBackground(new java.awt.Color(0, 0, 255));
        panelRound9.setRoundBottonLeft(120);
        panelRound9.setRoundBottonRight(120);
        panelRound9.setRoundTopLeft(120);
        panelRound9.setRoundTopRight(120);

        imageAvatarInWork.setForeground(new java.awt.Color(0, 0, 255));
        imageAvatarInWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/ThanhVy.png"))); // NOI18N

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(imageAvatarInWork, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(imageAvatarInWork, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        palMenu.setBackground(new java.awt.Color(102, 102, 102));
        palMenu.setForeground(new java.awt.Color(51, 51, 51));
        palMenu.setRoundBottonLeft(30);
        palMenu.setRoundBottonRight(30);
        palMenu.setRoundTopLeft(30);
        palMenu.setRoundTopRight(30);

        btnDashBoard.setBackground(new java.awt.Color(204, 204, 204));
        btnDashBoard.setRoundTopLeft(30);

        btnDashBoard1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnDashBoard1.setForeground(new java.awt.Color(102, 102, 102));
        btnDashBoard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashBoard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/dashboard.256x256.png"))); // NOI18N
        btnDashBoard1.setText("Dash Board");
        btnDashBoard1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashBoard1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDashBoard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDashBoardLayout = new javax.swing.GroupLayout(btnDashBoard);
        btnDashBoard.setLayout(btnDashBoardLayout);
        btnDashBoardLayout.setHorizontalGroup(
            btnDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        btnDashBoardLayout.setVerticalGroup(
            btnDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashBoard1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnFiles.setBackground(new java.awt.Color(204, 204, 204));

        btnFiles1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnFiles1.setForeground(new java.awt.Color(102, 102, 102));
        btnFiles1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFiles1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/project.256x243.png"))); // NOI18N
        btnFiles1.setText("Files");
        btnFiles1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiles1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFiles1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiles1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFiles1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFiles1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFilesLayout = new javax.swing.GroupLayout(btnFiles);
        btnFiles.setLayout(btnFilesLayout);
        btnFilesLayout.setHorizontalGroup(
            btnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFiles1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        btnFilesLayout.setVerticalGroup(
            btnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFiles1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        btnNotes.setBackground(new java.awt.Color(204, 204, 204));
        btnNotes.setRoundTopRight(30);

        btnNotes1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnNotes1.setForeground(new java.awt.Color(102, 102, 102));
        btnNotes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNotes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/dashboard.256x256.png"))); // NOI18N
        btnNotes1.setText("Notes");
        btnNotes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotes1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotes1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNotes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNotes1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNotesLayout = new javax.swing.GroupLayout(btnNotes);
        btnNotes.setLayout(btnNotesLayout);
        btnNotesLayout.setHorizontalGroup(
            btnNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNotes1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        btnNotesLayout.setVerticalGroup(
            btnNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNotes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        btnEmail.setBackground(new java.awt.Color(204, 204, 204));

        btnEmail1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnEmail1.setForeground(new java.awt.Color(102, 102, 102));
        btnEmail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/email.256x175.png"))); // NOI18N
        btnEmail1.setText("Emails");
        btnEmail1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmail1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmail1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmail1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmail1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEmailLayout = new javax.swing.GroupLayout(btnEmail);
        btnEmail.setLayout(btnEmailLayout);
        btnEmailLayout.setHorizontalGroup(
            btnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        btnEmailLayout.setVerticalGroup(
            btnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmail1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        btnSetting.setBackground(new java.awt.Color(204, 204, 204));
        btnSetting.setRoundBottonLeft(30);

        btnSetting1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnSetting1.setForeground(new java.awt.Color(102, 102, 102));
        btnSetting1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSetting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/settings-outline.249x256.png"))); // NOI18N
        btnSetting1.setText("Setting");
        btnSetting1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetting1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSetting1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSetting1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSettingLayout = new javax.swing.GroupLayout(btnSetting);
        btnSetting.setLayout(btnSettingLayout);
        btnSettingLayout.setHorizontalGroup(
            btnSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSetting1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        btnSettingLayout.setVerticalGroup(
            btnSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSetting1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        btnCalendar.setBackground(new java.awt.Color(204, 204, 204));
        btnCalendar.setRoundBottonRight(30);

        btnCalendar1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnCalendar1.setForeground(new java.awt.Color(102, 102, 102));
        btnCalendar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalendar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/calendar-schedule.242x256.png"))); // NOI18N
        btnCalendar1.setText("Calendar");
        btnCalendar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalendar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalendar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalendar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalendar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalendar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCalendarLayout = new javax.swing.GroupLayout(btnCalendar);
        btnCalendar.setLayout(btnCalendarLayout);
        btnCalendarLayout.setHorizontalGroup(
            btnCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        btnCalendarLayout.setVerticalGroup(
            btnCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalendar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout palMenuLayout = new javax.swing.GroupLayout(palMenu);
        palMenu.setLayout(palMenuLayout);
        palMenuLayout.setHorizontalGroup(
            palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(palMenuLayout.createSequentialGroup()
                        .addGroup(palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(palMenuLayout.createSequentialGroup()
                                .addComponent(btnDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palMenuLayout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        palMenuLayout.setVerticalGroup(
            palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(palMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palMenuLayout.createSequentialGroup()
                    .addContainerGap(288, Short.MAX_VALUE)
                    .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pal_AllMainLayout = new javax.swing.GroupLayout(pal_AllMain);
        pal_AllMain.setLayout(pal_AllMainLayout);
        pal_AllMainLayout.setHorizontalGroup(
            pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_AllMainLayout.createSequentialGroup()
                .addGroup(pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pal_AllMainLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pal_AllMainLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblNameUser))
                    .addGroup(pal_AllMainLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailUser))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pal_AllMainLayout.setVerticalGroup(
            pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_AllMainLayout.createSequentialGroup()
                .addGroup(pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pal_AllMainLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblNameUser)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailUser)
                        .addGap(70, 70, 70)
                        .addComponent(palMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pal_AllMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pal_Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(palSettingLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pal_AllMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pal_Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palSettingLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pal_AllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NotesMouseClicked
        // TODO add your handling code here:
//        switchPanels(palNotes);
    }//GEN-LAST:event_btn_NotesMouseClicked

    private void btn_SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseClicked
        // TODO add your handling code here:
//        switchPanels(palSettings);
    }//GEN-LAST:event_btn_SettingMouseClicked

    private void btnDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoardMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDashBoardMouseClicked

    private void btnNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotesMouseClicked

    private void btnFilesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilesMouseEntered

    private void btnFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilesMouseClicked

    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingMouseClicked

    private void btnCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarMouseClicked

    private void btn_VeChungToiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VeChungToiMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btn_VeChungToi);
    }//GEN-LAST:event_btn_VeChungToiMouseEntered

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnReport);
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnChinhSachNguoiDungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSachNguoiDungMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnChinhSachNguoiDung);
    }//GEN-LAST:event_btnChinhSachNguoiDungMouseEntered

    private void btn_VeChungToiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VeChungToiMouseExited
        // TODO add your handling code here:
        btn_VeChungToi.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btn_VeChungToiMouseExited

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        btnReport.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnReportMouseExited

    private void btnChinhSachNguoiDungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSachNguoiDungMouseExited
        // TODO add your handling code here:
        btnChinhSachNguoiDung.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnChinhSachNguoiDungMouseExited

    private void btnUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserNameMouseClicked

    private void btnUserNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNameMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnUserName);
    }//GEN-LAST:event_btnUserNameMouseEntered

    private void btnUserNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNameMouseExited
        // TODO add your handling code here:
        btnUserName.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnUserNameMouseExited

    private void lblNontificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontificationMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(1);
    }//GEN-LAST:event_lblNontificationMouseExited

    private void lblNontificationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontificationMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(1);
    }//GEN-LAST:event_lblNontificationMouseEntered

    private void lblNontificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontificationMouseClicked
        // TODO add your handling code here:
  

    }//GEN-LAST:event_lblNontificationMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(0);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(0);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblChartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChartMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(2);
    }//GEN-LAST:event_lblChartMouseEntered

    private void lblChartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChartMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(2);
    }//GEN-LAST:event_lblChartMouseExited

    private void lblCloudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloudMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(3);
    }//GEN-LAST:event_lblCloudMouseEntered

    private void lblCloudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloudMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(3);
    }//GEN-LAST:event_lblCloudMouseExited

    private void lblFavorateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavorateMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(4);
    }//GEN-LAST:event_lblFavorateMouseEntered

    private void lblFavorateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavorateMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(4);
    }//GEN-LAST:event_lblFavorateMouseExited

    private void lblHomePageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(5);
    }//GEN-LAST:event_lblHomePageMouseEntered

    private void lblHomePageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(5);
    }//GEN-LAST:event_lblHomePageMouseExited

    private void imageAvatarUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageAvatarUser1MouseEntered

    private void imageAvatarUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageAvatarUser1MouseExited

    private void imageAvatarUser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageAvatarUser2MouseEntered

    private void imageAvatarUser2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageAvatarUser2MouseExited

    private void imageAvatarUser3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser3MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageAvatarUser3MouseEntered

    private void imageAvatarUser3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser3MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_imageAvatarUser3MousePressed

    private void imageAvatarUser3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser3MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_imageAvatarUser3MouseExited

    private void imageAvatarUser4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser4MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_imageAvatarUser4MouseEntered

    private void imageAvatarUser4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser4MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageAvatarUser4MouseExited

    private void palSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palSearchMouseEntered
        // TODO add your handling code here:
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-text-cursor-24.png")).getImage(), new Point(0, 0), "Custom cursor");
        setCursor(cursor);
    }//GEN-LAST:event_palSearchMouseEntered

    private void palSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palSearchMouseExited
        // TODO add your handling code here:
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-mouse-40.png")).getImage(), new Point(0, 0), "Custom cursor");
        setCursor(cursor);
    }//GEN-LAST:event_palSearchMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn có chắc chắn muốn thoát ứng dụng?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void btn_VeChungToiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VeChungToiMouseClicked
        // TODO add your handling code here:
        new GioiThieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btn_VeChungToiMouseClicked

    private void pal_HeadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pal_HeadMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_pal_HeadMouseClicked

    private void lblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChucVuMouseClicked
        // TODO add your handling code here:
         new GioiThieuJDialog(this,true).setVisible(true);
   
    }//GEN-LAST:event_lblChucVuMouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void imageAvatar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar4MouseEntered
        // TODO add your handling code here:
         imageAvatar4.setBounds(imageAvatar4.getX()-5, imageAvatar4.getY()-5,imageAvatar4.getWidth()+10,  imageAvatar4.getHeight()+10);
    }//GEN-LAST:event_imageAvatar4MouseEntered

    private void imageAvatar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar4MouseExited
        // TODO add your handling code here:
        imageAvatar4.setBounds(imageAvatar4.getX()+5, imageAvatar4.getY()+5,imageAvatar4.getWidth()-10,  imageAvatar4.getHeight()-10);
    }//GEN-LAST:event_imageAvatar4MouseExited

    private void imageAvatar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar3MouseEntered
        // TODO add your handling code here:
        imageAvatar3.setBounds(imageAvatar3.getX()-5, imageAvatar3.getY()-5,imageAvatar3.getWidth()+10,  imageAvatar3.getHeight()+10);
    }//GEN-LAST:event_imageAvatar3MouseEntered

    private void imageAvatar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar3MouseExited
        // TODO add your handling code here:
         imageAvatar3.setBounds(imageAvatar3.getX()+5, imageAvatar3.getY()+5,imageAvatar3.getWidth()-10,  imageAvatar3.getHeight()-10);
    }//GEN-LAST:event_imageAvatar3MouseExited

    private void imageAvatar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar2MouseEntered
        // TODO add your handling code here:
        imageAvatar2.setBounds(imageAvatar2.getX()-5, imageAvatar2.getY()-5,imageAvatar2.getWidth()+10,  imageAvatar2.getHeight()+10);
    }//GEN-LAST:event_imageAvatar2MouseEntered

    private void imageAvatar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar2MouseExited
        // TODO add your handling code here:
        imageAvatar2.setBounds(imageAvatar2.getX()+5, imageAvatar2.getY()+5,imageAvatar2.getWidth()-10,  imageAvatar2.getHeight()-10);
    }//GEN-LAST:event_imageAvatar2MouseExited

    private void imageAvatar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar1MouseEntered
        // TODO add your handling code here:
        imageAvatar1.setBounds(imageAvatar1.getX()-5, imageAvatar1.getY()-5,imageAvatar1.getWidth()+10,  imageAvatar1.getHeight()+10);
    }//GEN-LAST:event_imageAvatar1MouseEntered

    private void imageAvatar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar1MouseExited
        // TODO add your handling code here:
        imageAvatar1.setBounds(imageAvatar1.getX()+5, imageAvatar1.getY()+5,imageAvatar1.getWidth()-10,  imageAvatar1.getHeight()-10);
    }//GEN-LAST:event_imageAvatar1MouseExited

    private void lblNontification1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontification1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNontification1MouseEntered

    private void lblNontification1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontification1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNontification1MouseExited

    private void lblNontification2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontification2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNontification2MouseEntered

    private void lblNontification2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontification2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNontification2MouseExited

    private void btnDashBoard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseClicked
        // TODO add your handling code here:
        indexForMenuMain=0;
        ClickEffectForPanel();
        panelTransactionAllMain.display(new DashBoardFrame());
    }//GEN-LAST:event_btnDashBoard1MouseClicked

    private void btnNotes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotes1MouseClicked
        // TODO add your handling code here:
        indexForMenuMain=1;
        ClickEffectForPanel();
        panelTransactionAllMain.display(new NotesFrame());
    }//GEN-LAST:event_btnNotes1MouseClicked

    private void btnEmail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmail1MouseClicked
        // TODO add your handling code here:
        indexForMenuMain=2;
        ClickEffectForPanel();
        panelTransactionAllMain.display(new EmailFrame());
    }//GEN-LAST:event_btnEmail1MouseClicked

    private void btnFiles1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiles1MouseClicked
        // TODO add your handling code here:
        indexForMenuMain=3;
        ClickEffectForPanel();
        panelTransactionAllMain.display(new FilesFrame());
    }//GEN-LAST:event_btnFiles1MouseClicked

    private void btnSetting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetting1MouseClicked
        // TODO add your handling code here:
        indexForMenuMain=4;
        ClickEffectForPanel();
        panelTransactionAllMain.display(new SettingFrame());
    }//GEN-LAST:event_btnSetting1MouseClicked

    private void btnCalendar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendar1MouseClicked
        // TODO add your handling code here:
        indexForMenuMain=5;
        ClickEffectForPanel();
        panelTransactionAllMain.display(new CalendarFrame());
    }//GEN-LAST:event_btnCalendar1MouseClicked

    private void btnDashBoard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnDashBoard1);
    }//GEN-LAST:event_btnDashBoard1MouseEntered

    private void btnDashBoard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnDashBoard1, 0);
    }//GEN-LAST:event_btnDashBoard1MouseExited

    private void btnNotes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotes1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnNotes1);
    }//GEN-LAST:event_btnNotes1MouseEntered

    private void btnNotes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotes1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnNotes1, 1);
    }//GEN-LAST:event_btnNotes1MouseExited

    private void btnEmail1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmail1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnEmail1, 2);
    }//GEN-LAST:event_btnEmail1MouseExited

    private void btnEmail1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmail1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnEmail1);
    }//GEN-LAST:event_btnEmail1MouseEntered

    private void btnFiles1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiles1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnFiles1);
    }//GEN-LAST:event_btnFiles1MouseEntered

    private void btnFiles1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiles1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnFiles1, 3);
    }//GEN-LAST:event_btnFiles1MouseExited

    private void btnSetting1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetting1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnSetting1);
    }//GEN-LAST:event_btnSetting1MouseEntered

    private void btnSetting1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetting1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnSetting1, 4);
    }//GEN-LAST:event_btnSetting1MouseExited

    private void btnCalendar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendar1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnCalendar1);
    }//GEN-LAST:event_btnCalendar1MouseEntered

    private void btnCalendar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendar1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnCalendar1, 5);
    }//GEN-LAST:event_btnCalendar1MouseExited

    private void txtSearchMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchMainActionPerformed
        // TODO add your handling code here:
        txtSearchMain.setText(null);
    }//GEN-LAST:event_txtSearchMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlbatdongsan.utils.PanelRound btnCalendar;
    private javax.swing.JLabel btnCalendar1;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnChart;
    private javax.swing.JLabel btnChinhSachNguoiDung;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnCloud;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnDashBoard;
    private javax.swing.JLabel btnDashBoard1;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnEmail;
    private javax.swing.JLabel btnEmail1;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnExit;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnFavorate;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnFiles;
    private javax.swing.JLabel btnFiles1;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnHomePage;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnNontification;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnNotes;
    private javax.swing.JLabel btnNotes1;
    private javax.swing.JLabel btnReport;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnSetting;
    private javax.swing.JLabel btnSetting1;
    private javax.swing.JLabel btnUserName;
    private javax.swing.JLabel btn_VeChungToi;
    private com.mycompany.qlbatdongsan.utils.ImageAvatar imageAvatar1;
    private com.mycompany.qlbatdongsan.utils.ImageAvatar imageAvatar2;
    private com.mycompany.qlbatdongsan.utils.ImageAvatar imageAvatar3;
    private com.mycompany.qlbatdongsan.utils.ImageAvatar imageAvatar4;
    private com.mycompany.qlbatdongsan.utils.ImageAvatar imageAvatarInWork;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblChart;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblCloud;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFavorate;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblNontification;
    private javax.swing.JLabel lblNontification1;
    private javax.swing.JLabel lblNontification2;
    private com.mycompany.qlbatdongsan.utils.PanelRound palMenu;
    private javax.swing.JPanel palSettingLeft;
    private javax.swing.JPanel pal_AllMain;
    private javax.swing.JPanel pal_Head;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound1;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound12;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound3;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound4;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound9;
    private com.mycompany.qlbatdongsan.utils.PanelTransaction panelTransactionAllMain;
    private javax.swing.JTextField txtSearchMain;
    // End of variables declaration//GEN-END:variables
}
