/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import java.awt.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author HO VAN DAT
 */
public class Main extends javax.swing.JFrame {

    private int[] status = {0, 1, 0, 0, 0, 0, 0, 0};
    private int indexForMenuMain = 1;

    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        ClickEffectForPanel();
        btnNotes1.setForeground(Color.BLUE);
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-mouse-40.png")).getImage(), new Point(0, 0), "Custom cursor");
        setCursor(cursor);
        panelTransactionAllMain.display(new NotesFrame());
    }

    //Hover for Label
    public void HoverForLabel(JLabel label) {
        label.setForeground(Color.BLUE);
    }
    //Hover effect for ImageAvatar
    public void HoverForImageAvatarEntered(int index){
        JComponent[] comp ={lblExit,lblNontification,lblChart,lblCloud,lblFavorate,lblHomePage};
        JPanel[] Panels ={btnExit,btnNotification,btnChart,btnCloud,btnFavorate,btnHomePage};
        Panels[index].setBounds(Panels[index].getX()-5, Panels[index].getY()-5,Panels[index].getWidth()+10,  Panels[index].getHeight()+10);
        comp[index].setBounds(comp[index].getX(), comp[index].getY(),comp[index].getWidth()+10,  comp[index].getHeight()+10);         
    }
    public void HoverForImageAvatarExited(int index){
        JComponent[] comp ={lblExit,lblNontification,lblChart,lblCloud,lblFavorate,lblHomePage};
        JPanel[] Panels ={btnExit,btnNotification,btnChart,btnCloud,btnFavorate,btnHomePage};
        Panels[index].setBounds(Panels[index].getX()+5, Panels[index].getY()+5,Panels[index].getWidth()-10,  Panels[index].getHeight()-10);
        comp[index].setBounds(comp[index].getX(), comp[index].getY(),comp[index].getWidth()-10,  comp[index].getHeight()-10);         
    }
    //Exited Effect
    public void ExitedForLabel(JLabel label, int statusID) {
        if (status[statusID] == 1) {
            label.setForeground(Color.BLUE);
        } else {
            label.setForeground(new Color(153,153,153));
        }
    }
    
    // Click Effect for panel
    public void ClickEffectForPanel() {

        JPanel[] panel = {btnDashBoard, btnNotes, btnEmail, btnSMS, btnFiles, btnClients, btnSetting, btnCalendar};
         JLabel[] label = {btnDashBoard1, btnNotes1, btnEmail1, btnSMS1, btnFiles1, btnClients1, btnSetting1, btnCalendar1};
        for (int i = 0; i < 8; i++) {
            if (indexForMenuMain == i) {
                panel[i].setBackground(new Color(255, 255, 255));
                label[i].setForeground(Color.BLUE);
            } else {
                panel[i].setBackground(new Color(204,204,204));
                label[i].setForeground(new Color(153,153,153));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar2 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar3 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar4 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar5 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar6 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar7 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar8 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar9 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatar10 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        pal_Head = new javax.swing.JPanel();
        btn_VeChungToi = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        btnChinhSachNguoiDung = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        btnUserName = new javax.swing.JLabel();
        btn_Logo = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblLogo = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        palSearch = new com.mycompany.qlbatdongsan.ui.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JLabel();
        lblIconTimKiem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblExit = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        btnNotification = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblNontification = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        palSettingLeft = new javax.swing.JPanel();
        btnChart = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblChart = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        btnCloud = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblCloud = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        btnFavorate = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblFavorate = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        btnHomePage = new com.mycompany.qlbatdongsan.ui.PanelRound();
        lblHomePage = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatarUser3 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatarUser4 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatarUser2 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        imageAvatarUser1 = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        pal_AllMain = new javax.swing.JPanel();
        lblNameUser = new javax.swing.JLabel();
        lblEmailUser = new javax.swing.JLabel();
        imageAvatarUser = new com.mycompany.qlbatdongsan.ui.ImageAvatar();
        panelRound1 = new com.mycompany.qlbatdongsan.ui.PanelRound();
        panelTransactionAllMain = new com.mycompany.qlbatdongsan.utils.PanelTransaction();
        panelRound5 = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnDashBoard = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnDashBoard1 = new javax.swing.JLabel();
        btnNotes = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnNotes1 = new javax.swing.JLabel();
        btnEmail = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnEmail1 = new javax.swing.JLabel();
        btnSMS = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnSMS1 = new javax.swing.JLabel();
        btnFiles = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnFiles1 = new javax.swing.JLabel();
        btnClients = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnClients1 = new javax.swing.JLabel();
        btnSetting = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnSetting1 = new javax.swing.JLabel();
        btnCalendar = new com.mycompany.qlbatdongsan.ui.PanelRound();
        btnCalendar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pal_Head.setBackground(new java.awt.Color(204, 204, 204));

        btn_VeChungToi.setBackground(new java.awt.Color(153, 153, 153));
        btn_VeChungToi.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_VeChungToi.setForeground(new java.awt.Color(102, 102, 102));
        btn_VeChungToi.setText("Về chúng tôi");
        btn_VeChungToi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_VeChungToiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_VeChungToiMouseExited(evt);
            }
        });

        lblChucVu.setBackground(new java.awt.Color(153, 153, 153));
        lblChucVu.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(102, 102, 102));
        lblChucVu.setText("Quản lý");

        btnChinhSachNguoiDung.setBackground(new java.awt.Color(153, 153, 153));
        btnChinhSachNguoiDung.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnChinhSachNguoiDung.setForeground(new java.awt.Color(102, 102, 102));
        btnChinhSachNguoiDung.setText("Chính sách người dùng");
        btnChinhSachNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChinhSachNguoiDungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChinhSachNguoiDungMouseExited(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(153, 153, 153));
        btnReport.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnReport.setForeground(new java.awt.Color(102, 102, 102));
        btnReport.setText("Báo lỗi");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        btnUserName.setBackground(new java.awt.Color(102, 102, 102));
        btnUserName.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnUserName.setForeground(new java.awt.Color(102, 102, 102));
        btnUserName.setText("Đạt Hồ");
        btnUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserNameMouseExited(evt);
            }
        });

        btn_Logo.setBackground(new java.awt.Color(255, 255, 255));
        btn_Logo.setRoundBottonLeft(50);
        btn_Logo.setRoundBottonRight(50);
        btn_Logo.setRoundTopLeft(50);
        btn_Logo.setRoundTopRight(50);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-circled-menu-30.png"))); // NOI18N

        javax.swing.GroupLayout btn_LogoLayout = new javax.swing.GroupLayout(btn_Logo);
        btn_Logo.setLayout(btn_LogoLayout);
        btn_LogoLayout.setHorizontalGroup(
            btn_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_LogoLayout.setVerticalGroup(
            btn_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LogoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        palSearch.setBackground(new java.awt.Color(255, 255, 255));
        palSearch.setRoundBottonLeft(50);
        palSearch.setRoundBottonRight(50);
        palSearch.setRoundTopLeft(50);
        palSearch.setRoundTopRight(50);
        palSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                palSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                palSearchMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Tìm kiếm dự án, khách hàng và hợp đồng");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(102, 102, 102));
        btnTimKiem.setText(">");

        lblIconTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/search.256x256.png"))); // NOI18N

        javax.swing.GroupLayout palSearchLayout = new javax.swing.GroupLayout(palSearch);
        palSearch.setLayout(palSearchLayout);
        palSearchLayout.setHorizontalGroup(
            palSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palSearchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblIconTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addGap(22, 22, 22))
        );
        palSearchLayout.setVerticalGroup(
            palSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palSearchLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(palSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconTimKiem)
                    .addGroup(palSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/user-circle.256x256.png"))); // NOI18N

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setRoundBottonLeft(50);
        btnExit.setRoundBottonRight(50);
        btnExit.setRoundTopLeft(50);
        btnExit.setRoundTopRight(50);

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/times-circle.256x256.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnNotification.setBackground(new java.awt.Color(255, 255, 255));
        btnNotification.setRoundBottonLeft(50);
        btnNotification.setRoundBottonRight(50);
        btnNotification.setRoundTopLeft(50);
        btnNotification.setRoundTopRight(50);

        lblNontification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/notification-solid.235x256.png"))); // NOI18N
        lblNontification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNontificationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNontificationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNontificationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNotificationLayout = new javax.swing.GroupLayout(btnNotification);
        btnNotification.setLayout(btnNotificationLayout);
        btnNotificationLayout.setHorizontalGroup(
            btnNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNotificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNontification, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnNotificationLayout.setVerticalGroup(
            btnNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNotificationLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblNontification, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pal_HeadLayout = new javax.swing.GroupLayout(pal_Head);
        pal_Head.setLayout(pal_HeadLayout);
        pal_HeadLayout.setHorizontalGroup(
            pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_HeadLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btn_VeChungToi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReport)
                .addGap(20, 20, 20)
                .addComponent(btnChinhSachNguoiDung)
                .addGap(79, 79, 79)
                .addComponent(palSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pal_HeadLayout.setVerticalGroup(
            pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_HeadLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pal_HeadLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(pal_HeadLayout.createSequentialGroup()
                .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pal_HeadLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChucVu)
                            .addComponent(btn_VeChungToi)
                            .addComponent(btnReport)
                            .addComponent(btnChinhSachNguoiDung)))
                    .addGroup(pal_HeadLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pal_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        palSettingLeft.setBackground(new java.awt.Color(204, 204, 204));
        palSettingLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnChart.setBackground(new java.awt.Color(255, 255, 255));
        btnChart.setPreferredSize(new java.awt.Dimension(52, 49));
        btnChart.setRoundBottonLeft(50);
        btnChart.setRoundBottonRight(50);
        btnChart.setRoundTopLeft(50);
        btnChart.setRoundTopRight(50);

        lblChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-financial-crisis-30.png"))); // NOI18N
        lblChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblChartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnChartLayout = new javax.swing.GroupLayout(btnChart);
        btnChart.setLayout(btnChartLayout);
        btnChartLayout.setHorizontalGroup(
            btnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnChartLayout.setVerticalGroup(
            btnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChartLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblChart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnCloud.setBackground(new java.awt.Color(255, 255, 255));
        btnCloud.setPreferredSize(new java.awt.Dimension(52, 49));
        btnCloud.setRoundBottonLeft(50);
        btnCloud.setRoundBottonRight(50);
        btnCloud.setRoundTopLeft(50);
        btnCloud.setRoundTopRight(50);

        lblCloud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/cloud.png"))); // NOI18N
        lblCloud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloudMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloudLayout = new javax.swing.GroupLayout(btnCloud);
        btnCloud.setLayout(btnCloudLayout);
        btnCloudLayout.setHorizontalGroup(
            btnCloudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCloud, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCloudLayout.setVerticalGroup(
            btnCloudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloudLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCloud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnFavorate.setBackground(new java.awt.Color(255, 255, 255));
        btnFavorate.setRoundBottonLeft(50);
        btnFavorate.setRoundBottonRight(50);
        btnFavorate.setRoundTopLeft(50);
        btnFavorate.setRoundTopRight(50);

        lblFavorate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-favorite-database-30.png"))); // NOI18N
        lblFavorate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFavorateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFavorateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFavorateLayout = new javax.swing.GroupLayout(btnFavorate);
        btnFavorate.setLayout(btnFavorateLayout);
        btnFavorateLayout.setHorizontalGroup(
            btnFavorateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFavorateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFavorate, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnFavorateLayout.setVerticalGroup(
            btnFavorateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFavorateLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblFavorate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnHomePage.setBackground(new java.awt.Color(255, 255, 255));
        btnHomePage.setRoundBottonLeft(50);
        btnHomePage.setRoundBottonRight(50);
        btnHomePage.setRoundTopLeft(50);
        btnHomePage.setRoundTopRight(50);

        lblHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/world.256x256.png"))); // NOI18N
        lblHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomePageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomePageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHomePageLayout = new javax.swing.GroupLayout(btnHomePage);
        btnHomePage.setLayout(btnHomePageLayout);
        btnHomePageLayout.setHorizontalGroup(
            btnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnHomePageLayout.setVerticalGroup(
            btnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomePageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        imageAvatarUser3.setForeground(new java.awt.Color(0, 0, 255));
        imageAvatarUser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/DatHo.png"))); // NOI18N
        imageAvatarUser3.setPreferredSize(new java.awt.Dimension(52, 49));
        imageAvatarUser3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatarUser3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatarUser3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageAvatarUser3MousePressed(evt);
            }
        });

        imageAvatarUser4.setForeground(new java.awt.Color(0, 0, 255));
        imageAvatarUser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/ThuThuy.png"))); // NOI18N
        imageAvatarUser4.setPreferredSize(new java.awt.Dimension(52, 49));
        imageAvatarUser4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatarUser4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatarUser4MouseExited(evt);
            }
        });

        imageAvatarUser2.setForeground(new java.awt.Color(0, 0, 255));
        imageAvatarUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/ThanhVySv2.png"))); // NOI18N
        imageAvatarUser2.setPreferredSize(new java.awt.Dimension(52, 49));
        imageAvatarUser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatarUser2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatarUser2MouseExited(evt);
            }
        });

        imageAvatarUser1.setForeground(new java.awt.Color(0, 0, 255));
        imageAvatarUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/NgPhu.png"))); // NOI18N
        imageAvatarUser1.setPreferredSize(new java.awt.Dimension(52, 49));
        imageAvatarUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageAvatarUser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageAvatarUser1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout palSettingLeftLayout = new javax.swing.GroupLayout(palSettingLeft);
        palSettingLeft.setLayout(palSettingLeftLayout);
        palSettingLeftLayout.setHorizontalGroup(
            palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palSettingLeftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageAvatarUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatarUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatarUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatarUser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFavorate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        palSettingLeftLayout.setVerticalGroup(
            palSettingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palSettingLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCloud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFavorate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageAvatarUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(imageAvatarUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(imageAvatarUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(imageAvatarUser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pal_AllMain.setBackground(new java.awt.Color(204, 204, 204));
        pal_AllMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblNameUser.setFont(new java.awt.Font("Roboto Slab Thin", 1, 14)); // NOI18N
        lblNameUser.setForeground(new java.awt.Color(51, 51, 51));
        lblNameUser.setText("Hello Vỵ Mặt LOL");

        lblEmailUser.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        lblEmailUser.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailUser.setText("wtsdatho@gmail.com");

        imageAvatarUser.setForeground(new java.awt.Color(0, 0, 255));
        imageAvatarUser.setBorderSize(2);
        imageAvatarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/ThanhVy.png"))); // NOI18N

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottonLeft(30);
        panelRound1.setRoundBottonRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransactionAllMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransactionAllMain, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );

        panelRound5.setBackground(new java.awt.Color(153, 153, 153));
        panelRound5.setRoundBottonLeft(30);
        panelRound5.setRoundBottonRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);

        btnDashBoard.setBackground(new java.awt.Color(204, 204, 204));
        btnDashBoard.setPreferredSize(new java.awt.Dimension(90, 90));
        btnDashBoard.setRoundTopLeft(30);
        btnDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashBoardMouseClicked(evt);
            }
        });

        btnDashBoard1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDashBoard1.setForeground(new java.awt.Color(153, 153, 153));
        btnDashBoard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashBoard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/dashboard.256x256.png"))); // NOI18N
        btnDashBoard1.setText("Dashboard");
        btnDashBoard1.setToolTipText("");
        btnDashBoard1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashBoard1.setPreferredSize(new java.awt.Dimension(68, 65));
        btnDashBoard1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDashBoard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDashBoardLayout = new javax.swing.GroupLayout(btnDashBoard);
        btnDashBoard.setLayout(btnDashBoardLayout);
        btnDashBoardLayout.setHorizontalGroup(
            btnDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashBoard1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnDashBoardLayout.setVerticalGroup(
            btnDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashBoard1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        btnNotes.setBackground(new java.awt.Color(204, 204, 204));
        btnNotes.setPreferredSize(new java.awt.Dimension(90, 90));
        btnNotes.setRoundTopRight(30);
        btnNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotesMouseClicked(evt);
            }
        });

        btnNotes1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNotes1.setForeground(new java.awt.Color(153, 153, 153));
        btnNotes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNotes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/Notes.png"))); // NOI18N
        btnNotes1.setText("Công việc");
        btnNotes1.setToolTipText("");
        btnNotes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotes1.setPreferredSize(new java.awt.Dimension(71, 65));
        btnNotes1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotes1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNotes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNotes1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNotesLayout = new javax.swing.GroupLayout(btnNotes);
        btnNotes.setLayout(btnNotesLayout);
        btnNotesLayout.setHorizontalGroup(
            btnNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNotes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNotesLayout.setVerticalGroup(
            btnNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNotes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnEmail.setBackground(new java.awt.Color(204, 204, 204));
        btnEmail.setPreferredSize(new java.awt.Dimension(90, 90));

        btnEmail1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEmail1.setForeground(new java.awt.Color(153, 153, 153));
        btnEmail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/email.256x175.png"))); // NOI18N
        btnEmail1.setText("Email");
        btnEmail1.setToolTipText("");
        btnEmail1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmail1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmail1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmail1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmail1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEmailLayout = new javax.swing.GroupLayout(btnEmail);
        btnEmail.setLayout(btnEmailLayout);
        btnEmailLayout.setHorizontalGroup(
            btnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEmailLayout.setVerticalGroup(
            btnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmail1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        btnSMS.setBackground(new java.awt.Color(204, 204, 204));
        btnSMS.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSMSMouseClicked(evt);
            }
        });

        btnSMS1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSMS1.setForeground(new java.awt.Color(153, 153, 153));
        btnSMS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSMS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/messenger.256x256.png"))); // NOI18N
        btnSMS1.setText("SMS");
        btnSMS1.setToolTipText("");
        btnSMS1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSMS1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSMS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSMS1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSMS1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSMS1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSMSLayout = new javax.swing.GroupLayout(btnSMS);
        btnSMS.setLayout(btnSMSLayout);
        btnSMSLayout.setHorizontalGroup(
            btnSMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSMS1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnSMSLayout.setVerticalGroup(
            btnSMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSMS1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        btnFiles.setBackground(new java.awt.Color(204, 204, 204));
        btnFiles.setPreferredSize(new java.awt.Dimension(90, 90));
        btnFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFilesMouseEntered(evt);
            }
        });

        btnFiles1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFiles1.setForeground(new java.awt.Color(153, 153, 153));
        btnFiles1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFiles1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/project.256x243.png"))); // NOI18N
        btnFiles1.setText("Tệp");
        btnFiles1.setToolTipText("");
        btnFiles1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiles1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFiles1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiles1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFiles1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFiles1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFilesLayout = new javax.swing.GroupLayout(btnFiles);
        btnFiles.setLayout(btnFilesLayout);
        btnFilesLayout.setHorizontalGroup(
            btnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFiles1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnFilesLayout.setVerticalGroup(
            btnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFiles1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        btnClients.setBackground(new java.awt.Color(204, 204, 204));
        btnClients.setPreferredSize(new java.awt.Dimension(90, 90));
        btnClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientsMouseClicked(evt);
            }
        });

        btnClients1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnClients1.setForeground(new java.awt.Color(153, 153, 153));
        btnClients1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/nhanvien.png"))); // NOI18N
        btnClients1.setText("  Nhân viên");
        btnClients1.setToolTipText("");
        btnClients1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClients1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClients1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClients1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClients1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClients1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnClientsLayout = new javax.swing.GroupLayout(btnClients);
        btnClients.setLayout(btnClientsLayout);
        btnClientsLayout.setHorizontalGroup(
            btnClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClients1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnClientsLayout.setVerticalGroup(
            btnClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClients1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        btnSetting.setBackground(new java.awt.Color(204, 204, 204));
        btnSetting.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSetting.setRoundBottonLeft(30);
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingMouseClicked(evt);
            }
        });

        btnSetting1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSetting1.setForeground(new java.awt.Color(153, 153, 153));
        btnSetting1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSetting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/settings-outline.249x256.png"))); // NOI18N
        btnSetting1.setText("Cài đặt");
        btnSetting1.setToolTipText("");
        btnSetting1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetting1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSetting1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSetting1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSettingLayout = new javax.swing.GroupLayout(btnSetting);
        btnSetting.setLayout(btnSettingLayout);
        btnSettingLayout.setHorizontalGroup(
            btnSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSetting1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnSettingLayout.setVerticalGroup(
            btnSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSetting1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        btnCalendar.setBackground(new java.awt.Color(204, 204, 204));
        btnCalendar.setPreferredSize(new java.awt.Dimension(90, 90));
        btnCalendar.setRoundBottonRight(30);
        btnCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalendarMouseClicked(evt);
            }
        });

        btnCalendar1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCalendar1.setForeground(new java.awt.Color(153, 153, 153));
        btnCalendar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalendar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/calendar-schedule.242x256.png"))); // NOI18N
        btnCalendar1.setText("Lịch");
        btnCalendar1.setToolTipText("");
        btnCalendar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalendar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalendar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalendar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalendar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalendar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCalendarLayout = new javax.swing.GroupLayout(btnCalendar);
        btnCalendar.setLayout(btnCalendarLayout);
        btnCalendarLayout.setHorizontalGroup(
            btnCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalendar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnCalendarLayout.setVerticalGroup(
            btnCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalendar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRound5Layout.createSequentialGroup()
                                .addComponent(btnSMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound5Layout.createSequentialGroup()
                                .addComponent(btnFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound5Layout.createSequentialGroup()
                                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout pal_AllMainLayout = new javax.swing.GroupLayout(pal_AllMain);
        pal_AllMain.setLayout(pal_AllMainLayout);
        pal_AllMainLayout.setHorizontalGroup(
            pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_AllMainLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_AllMainLayout.createSequentialGroup()
                        .addComponent(imageAvatarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_AllMainLayout.createSequentialGroup()
                        .addComponent(lblNameUser)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_AllMainLayout.createSequentialGroup()
                        .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_AllMainLayout.createSequentialGroup()
                        .addComponent(lblEmailUser)
                        .addGap(67, 67, 67)))
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pal_AllMainLayout.setVerticalGroup(
            pal_AllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_AllMainLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(imageAvatarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblNameUser)
                .addGap(18, 18, 18)
                .addComponent(lblEmailUser)
                .addGap(71, 71, 71)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_AllMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pal_Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(palSettingLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(pal_AllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pal_Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palSettingLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pal_AllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NotesMouseClicked
        // TODO add your handling code here:
//        switchPanels(palNotes);
    }//GEN-LAST:event_btn_NotesMouseClicked

    private void btn_SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseClicked
        // TODO add your handling code here:
//        switchPanels(palSettings);
    }//GEN-LAST:event_btn_SettingMouseClicked

    private void btnNotes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotes1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new NotesFrame());
        indexForMenuMain = 1;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
            status[i] = 0;
        }
        status[1] = 1;
    }//GEN-LAST:event_btnNotes1MouseClicked

    private void btnDashBoard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new DashBoardFrame());
        indexForMenuMain = 0;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
            status[i] = 0;
        }
        status[0] = 1;
    }//GEN-LAST:event_btnDashBoard1MouseClicked

    private void btnEmail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmail1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new EmailFrame());
        indexForMenuMain = 2;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
            status[i] = 0;
        }
        status[2] = 1;
    }//GEN-LAST:event_btnEmail1MouseClicked

    private void btnDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoardMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDashBoardMouseClicked

    private void btnNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotesMouseClicked

    private void btnSMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSMSMouseClicked

    private void btnFilesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilesMouseEntered

    private void btnFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilesMouseClicked

    private void btnClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientsMouseClicked

    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingMouseClicked

    private void btnCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarMouseClicked

    private void btnSMS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMS1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new SMSFrame());
        indexForMenuMain = 3;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
            status[i] = 0;
        }
        status[3] = 1;
    }//GEN-LAST:event_btnSMS1MouseClicked

    private void btnFiles1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiles1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new FilesFrame());
        indexForMenuMain = 4;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
           status[i]=0; 
        }
        status[4]=1;
    }//GEN-LAST:event_btnFiles1MouseClicked

    private void btnClients1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClients1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new ClientFrame());
        indexForMenuMain = 5;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
           status[i]=0; 
        }
        status[5]=1;
    }//GEN-LAST:event_btnClients1MouseClicked

    private void btnSetting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetting1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new SettingFrame());
        indexForMenuMain = 6;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
           status[i]=0; 
        }
        status[6]=1;
    }//GEN-LAST:event_btnSetting1MouseClicked

    private void btnCalendar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendar1MouseClicked
        // TODO add your handling code here:
        panelTransactionAllMain.display(new CalendarFrame());
        indexForMenuMain = 7;
        ClickEffectForPanel();
        for (int i = 0; i < 8; i++) {
           status[i]=0; 
        }
        status[7]=1;
    }//GEN-LAST:event_btnCalendar1MouseClicked

    private void btn_VeChungToiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VeChungToiMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btn_VeChungToi);
    }//GEN-LAST:event_btn_VeChungToiMouseEntered

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnReport);
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnChinhSachNguoiDungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSachNguoiDungMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnChinhSachNguoiDung);
    }//GEN-LAST:event_btnChinhSachNguoiDungMouseEntered

    private void btn_VeChungToiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VeChungToiMouseExited
        // TODO add your handling code here:
        btn_VeChungToi.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btn_VeChungToiMouseExited

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        btnReport.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnReportMouseExited

    private void btnChinhSachNguoiDungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSachNguoiDungMouseExited
        // TODO add your handling code here:
        btnChinhSachNguoiDung.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnChinhSachNguoiDungMouseExited

    private void btnUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserNameMouseClicked

    private void btnUserNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNameMouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnUserName);
    }//GEN-LAST:event_btnUserNameMouseEntered

    private void btnUserNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNameMouseExited
        // TODO add your handling code here:
        btnUserName.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnUserNameMouseExited

    private void btnDashBoard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnDashBoard1);
    }//GEN-LAST:event_btnDashBoard1MouseEntered

    private void btnDashBoard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnDashBoard1, 0);
    }//GEN-LAST:event_btnDashBoard1MouseExited

    private void btnNotes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotes1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnNotes1);

    }//GEN-LAST:event_btnNotes1MouseEntered

    private void btnNotes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotes1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnNotes1, 1);
    }//GEN-LAST:event_btnNotes1MouseExited

    private void btnEmail1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmail1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnEmail1);
    }//GEN-LAST:event_btnEmail1MouseEntered

    private void btnEmail1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmail1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnEmail1, 2);
    }//GEN-LAST:event_btnEmail1MouseExited

    private void btnSMS1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMS1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnSMS1);
    }//GEN-LAST:event_btnSMS1MouseEntered

    private void btnSMS1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMS1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnSMS1, 3);
    }//GEN-LAST:event_btnSMS1MouseExited

    private void btnFiles1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiles1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnFiles1);
    }//GEN-LAST:event_btnFiles1MouseEntered

    private void btnFiles1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiles1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnFiles1, 4);
    }//GEN-LAST:event_btnFiles1MouseExited

    private void btnClients1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClients1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnClients1);
    }//GEN-LAST:event_btnClients1MouseEntered

    private void btnClients1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClients1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnClients1, 5);
    }//GEN-LAST:event_btnClients1MouseExited

    private void btnSetting1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetting1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnSetting1);
    }//GEN-LAST:event_btnSetting1MouseEntered

    private void btnSetting1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetting1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnSetting1, 6);
    }//GEN-LAST:event_btnSetting1MouseExited

    private void btnCalendar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendar1MouseEntered
        // TODO add your handling code here:
        HoverForLabel(btnCalendar1);
    }//GEN-LAST:event_btnCalendar1MouseEntered

    private void btnCalendar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendar1MouseExited
        // TODO add your handling code here:
        ExitedForLabel(btnCalendar1, 7);
    }//GEN-LAST:event_btnCalendar1MouseExited

    private void lblNontificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontificationMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(1);
    }//GEN-LAST:event_lblNontificationMouseExited

    private void lblNontificationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontificationMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(1);
    }//GEN-LAST:event_lblNontificationMouseEntered

    private void lblNontificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNontificationMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblNontificationMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(0);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(0);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblChartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChartMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(2);
    }//GEN-LAST:event_lblChartMouseEntered

    private void lblChartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChartMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(2);
    }//GEN-LAST:event_lblChartMouseExited

    private void lblCloudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloudMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(3);
    }//GEN-LAST:event_lblCloudMouseEntered

    private void lblCloudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloudMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(3);
    }//GEN-LAST:event_lblCloudMouseExited

    private void lblFavorateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavorateMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(4);
    }//GEN-LAST:event_lblFavorateMouseEntered

    private void lblFavorateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavorateMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(4);
    }//GEN-LAST:event_lblFavorateMouseExited

    private void lblHomePageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMouseEntered
        // TODO add your handling code here:
        HoverForImageAvatarEntered(5);
    }//GEN-LAST:event_lblHomePageMouseEntered

    private void lblHomePageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMouseExited
        // TODO add your handling code here:
        HoverForImageAvatarExited(5);
    }//GEN-LAST:event_lblHomePageMouseExited

    private void imageAvatarUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser1MouseEntered
        // TODO add your handling code here:
        imageAvatarUser1.setBounds(imageAvatarUser1.getX()-5, imageAvatarUser1.getY()-5,imageAvatarUser1.getWidth()+10,  imageAvatarUser1.getHeight()+10);
    }//GEN-LAST:event_imageAvatarUser1MouseEntered

    private void imageAvatarUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser1MouseExited
        // TODO add your handling code here:
        imageAvatarUser1.setBounds(imageAvatarUser1.getX()+5, imageAvatarUser1.getY()+5,imageAvatarUser1.getWidth()-10,  imageAvatarUser1.getHeight()-10);
    }//GEN-LAST:event_imageAvatarUser1MouseExited

    private void imageAvatarUser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser2MouseEntered
        // TODO add your handling code here:
        imageAvatarUser2.setBounds(imageAvatarUser2.getX()-5, imageAvatarUser2.getY()-5,imageAvatarUser2.getWidth()+10,  imageAvatarUser2.getHeight()+10);
    }//GEN-LAST:event_imageAvatarUser2MouseEntered

    private void imageAvatarUser2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser2MouseExited
        // TODO add your handling code here:
        imageAvatarUser2.setBounds(imageAvatarUser2.getX()+5, imageAvatarUser2.getY()+5,imageAvatarUser2.getWidth()-10,  imageAvatarUser2.getHeight()-10);
    }//GEN-LAST:event_imageAvatarUser2MouseExited

    private void imageAvatarUser3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser3MouseEntered
        // TODO add your handling code here:
        imageAvatarUser3.setBounds(imageAvatarUser3.getX()-5, imageAvatarUser3.getY()-5,imageAvatarUser3.getWidth()+10,  imageAvatarUser3.getHeight()+10);
    }//GEN-LAST:event_imageAvatarUser3MouseEntered

    private void imageAvatarUser3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser3MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_imageAvatarUser3MousePressed

    private void imageAvatarUser3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser3MouseExited
        // TODO add your handling code here:
        imageAvatarUser3.setBounds(imageAvatarUser3.getX()+5, imageAvatarUser3.getY()+5,imageAvatarUser3.getWidth()-10,  imageAvatarUser3.getHeight()-10);
    }//GEN-LAST:event_imageAvatarUser3MouseExited

    private void imageAvatarUser4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser4MouseEntered
        // TODO add your handling code here:
        imageAvatarUser4.setBounds(imageAvatarUser4.getX()-5, imageAvatarUser4.getY()-5,imageAvatarUser4.getWidth()+10,  imageAvatarUser4.getHeight()+10);
    }//GEN-LAST:event_imageAvatarUser4MouseEntered

    private void imageAvatarUser4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatarUser4MouseExited
        // TODO add your handling code here:
        imageAvatarUser4.setBounds(imageAvatarUser4.getX()+5, imageAvatarUser4.getY()+5,imageAvatarUser4.getWidth()-10,  imageAvatarUser4.getHeight()-10);
    }//GEN-LAST:event_imageAvatarUser4MouseExited

    private void palSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palSearchMouseEntered
        // TODO add your handling code here:
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-text-cursor-24.png")).getImage(), new Point(0, 0), "Custom cursor");
        setCursor(cursor);
    }//GEN-LAST:event_palSearchMouseEntered

    private void palSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palSearchMouseExited
        // TODO add your handling code here:
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-mouse-40.png")).getImage(), new Point(0, 0), "Custom cursor");
        setCursor(cursor);
    }//GEN-LAST:event_palSearchMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlbatdongsan.ui.PanelRound btnCalendar;
    private javax.swing.JLabel btnCalendar1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnChart;
    private javax.swing.JLabel btnChinhSachNguoiDung;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnClients;
    private javax.swing.JLabel btnClients1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnCloud;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnDashBoard;
    private javax.swing.JLabel btnDashBoard1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnEmail;
    private javax.swing.JLabel btnEmail1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnExit;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnFavorate;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnFiles;
    private javax.swing.JLabel btnFiles1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnHomePage;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnNotes;
    private javax.swing.JLabel btnNotes1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnNotification;
    private javax.swing.JLabel btnReport;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnSMS;
    private javax.swing.JLabel btnSMS1;
    private com.mycompany.qlbatdongsan.ui.PanelRound btnSetting;
    private javax.swing.JLabel btnSetting1;
    private javax.swing.JLabel btnTimKiem;
    private javax.swing.JLabel btnUserName;
    private com.mycompany.qlbatdongsan.ui.PanelRound btn_Logo;
    private javax.swing.JLabel btn_VeChungToi;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar1;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar10;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar2;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar3;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar4;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar5;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar6;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar7;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar8;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatar9;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatarUser;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatarUser1;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatarUser2;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatarUser3;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar imageAvatarUser4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblChart;
    private javax.swing.JLabel lblChucVu;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblCloud;
    private javax.swing.JLabel lblEmailUser;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblExit;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblFavorate;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblHomePage;
    private javax.swing.JLabel lblIconTimKiem;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblLogo;
    private javax.swing.JLabel lblNameUser;
    private com.mycompany.qlbatdongsan.ui.ImageAvatar lblNontification;
    private com.mycompany.qlbatdongsan.ui.PanelRound palSearch;
    private javax.swing.JPanel palSettingLeft;
    private javax.swing.JPanel pal_AllMain;
    private javax.swing.JPanel pal_Head;
    private com.mycompany.qlbatdongsan.ui.PanelRound panelRound1;
    private com.mycompany.qlbatdongsan.ui.PanelRound panelRound5;
    private com.mycompany.qlbatdongsan.utils.PanelTransaction panelTransactionAllMain;
    // End of variables declaration//GEN-END:variables
}
