/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.LichThanhToanDAO;
import com.mycompany.qlbatdongsan.DAO.QuanLyDuAnDAO;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.Entity.LichSuThanhToan;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HO VAN DAT
 */
public class ProjectFrame extends javax.swing.JPanel {

    DefaultTableModel model;
    static QuanLyDuAnDAO daoDA = new QuanLyDuAnDAO();
    int row = -1;
    static String SearchText = "";

    public ProjectFrame() {
        initComponents();
        initTableProject();
        fillTableDA();
    }

    public void initTableProject() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int i, int j) {
                return false;
            }
        };
        Object[] column = {"Mã dự án", "Tên dự án", "Địa chỉ", "Diện tích", "Số giấy phép", "Ngày cấp", "Nơi cấp", "Loaị DA", "Ngày đăng"};
        model.setColumnIdentifiers(column);
        model.setRowCount(0);

        tblProject.setModel(model);
    }

    static void fillTableDA() {
        DefaultTableModel model = (DefaultTableModel) tblProject.getModel();
        model.setRowCount(0);
        try {
            List<QuanLyDuAn> list = daoDA.selectAll();
            for (QuanLyDuAn da : list) {
                Object[] row = {
                    da.getMaDA(),
                    da.getTenDA(),
                    da.getDiaChi(),
                    da.getDienTich(),
                    da.getSoGiayPhep(),
                    da.getNgayCap(),
                    da.getNoiCap(),
                    da.getLoaiDA(),
                    da.getNgayDang()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("Lỗi truy vấn dữ liệu!");
        }
    }

    void edit() {
        QuanLyDuAn da = daoDA.selectById(tblProject.getValueAt(row, 0).toString());
        SeeProjectFrame manengerProjectFrame = new SeeProjectFrame(da);
        manengerProjectFrame.setVisible(true);
    }

    public static void Search(String str) {
        if (str.length() > 0) {
            if (tblProject != null) {
                DefaultTableModel model = (DefaultTableModel) tblProject.getModel();
                TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
                tblProject.setRowSorter(trs);
                trs.setRowFilter(RowFilter.regexFilter(str));
            } else {
                return;
            }
        }
        if (str.length()==0) {
            fillTableDA();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProject = new javax.swing.JTable();
        btnAddProject = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblAddProject = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("DỰ ÁN");

        tblProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjectMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProjectMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProject);

        btnAddProject.setRoundBottonLeft(30);
        btnAddProject.setRoundBottonRight(30);
        btnAddProject.setRoundTopLeft(30);
        btnAddProject.setRoundTopRight(30);

        lblAddProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-add-new-64.png"))); // NOI18N
        lblAddProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddProjectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddProjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddProjectMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddProjectLayout = new javax.swing.GroupLayout(btnAddProject);
        btnAddProject.setLayout(btnAddProjectLayout);
        btnAddProjectLayout.setHorizontalGroup(
            btnAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        btnAddProjectLayout.setVerticalGroup(
            btnAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(btnAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(btnAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblProjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjectMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblProjectMousePressed

    private void tblProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjectMouseClicked

        if (evt.getClickCount() == 2) {
            this.row = tblProject.rowAtPoint(evt.getPoint());
            edit();
        }
    }//GEN-LAST:event_tblProjectMouseClicked

    private void btnAddProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProjectMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAddProjectMouseEntered

    private void btnAddProjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProjectMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddProjectMouseExited

    private void btnAddProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProjectMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAddProjectMouseClicked

    private void lblAddProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddProjectMouseClicked
        // TODO add your handling code here:
        AddProjectFrame addProjectFrame = new AddProjectFrame();
        addProjectFrame.setVisible(true);
    }//GEN-LAST:event_lblAddProjectMouseClicked

    private void lblAddProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddProjectMouseEntered
        // TODO add your handling code here:
         btnAddProject.setBounds(btnAddProject.getX() - 5, btnAddProject.getY() - 5, btnAddProject.getWidth() + 10, btnAddProject.getHeight() + 10);
        lblAddProject.setBounds(lblAddProject.getX(), lblAddProject.getY(), lblAddProject.getWidth() + 10, lblAddProject.getHeight() + 10);
    }//GEN-LAST:event_lblAddProjectMouseEntered

    private void lblAddProjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddProjectMouseExited
        // TODO add your handling code here:
        btnAddProject.setBounds(btnAddProject.getX() + 5, btnAddProject.getY() + 5, btnAddProject.getWidth() - 10, btnAddProject.getHeight() - 10);
        lblAddProject.setBounds(lblAddProject.getX(), lblAddProject.getY(), lblAddProject.getWidth() - 10, lblAddProject.getHeight() - 10);
    }//GEN-LAST:event_lblAddProjectMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlbatdongsan.utils.PanelRound btnAddProject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddProject;
    private static javax.swing.JTable tblProject;
    // End of variables declaration//GEN-END:variables
}
