/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.TaiLieuDuAnDAO;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import com.mycompany.qlbatdongsan.Entity.TaiLieuDuAN;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author HO VAN DAT
 */
public class SeeProjectPanel extends javax.swing.JPanel {

    TaiLieuDuAnDAO daoImage = new TaiLieuDuAnDAO();
    QuanLyDuAn da;
    private int indexImage;

    /**
     * Creates new form SeeProjectPanel
     */
    public SeeProjectPanel(QuanLyDuAn entity) {
        initComponents();
        this.da = entity;
        ImageProject();
        indexImage = setIndexImage();
        SeeProject();
        SeeImageProject();
    }

    public int setIndexImage() {
        if (ImageProject() != null) {
            return ImageProject().size() - 1;
        }
        return -1;
    }

    public List<TaiLieuDuAN> ImageProject() {
        List<TaiLieuDuAN> list = daoImage.selectByIdmaDA(da.getMaDA());
        if (list != null) {
            return list;
        }
        return list = new ArrayList<>();
    }

    public void SeeProject() {
        if (ImageProject().isEmpty()) {
            MsgBox.alert(this, "Dự án vẫn chưa có hình ảnh vui lòng thêm hình ảnh trong mục chỉnh sửa!!!");
            lblImageDa.setText("Vẫn chưa thêm hình ảnh!");
        }

        lblSeeProject.setText("Dự án: " + da.getTenDA() + " có mã dự án " + da.getMaDA());
        lblSeeProject1.setText("Vị trí tọa lạc: " + da.getDiaChi());
        lblSeeProject2.setText("Chủ đầu tư: " + da.getChuDauTu());
        lblSeeProject6.setText("Loại hình sản phẩm: " + da.getLoaiHinhSP());
        lblSeeProject3.setText("Diện tích tổng quan: " + da.getTongDienTich() + "m2");
        lblSeeProject4.setText("Mật độ triển khai xây dựng dự án: " + da.getMatDo() + "%");
        lblSeeProject5.setText("Số  lượng sản phẩm: " + da.getSoLuongSanPham());
        lblSeeProject6.setText("Thiết kế: " + da.getKienTrucThietKe());
        lblSeeProject7.setText("Quy mô xây dựng: " + da.getQuyMo());
        lblSeeProject8.setText("Tính pháp lý: " + da.getPhapLy());
        lblSeeProject9.setText("Khởi công: " + da.getKhoiCong() + ";" + " hoàn thiện: " + da.getHoanThien() + ";" + " bàn giao: " + da.getBanGiao());
    }

    public void SeeImageProject() {
        try {
            for (int i = 0; i < ImageProject().size(); i++) {
                if (i == indexImage) {
                    lblImageDa.setIcon(new ImageIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\imgAvartar\\" + ImageProject().get(i).getHinh()).getImage().getScaledInstance(698, 372, Image.SCALE_DEFAULT)));
                    lblImageDa.setText(null);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Next() {
        if (indexImage == ImageProject().size() - 1) {
            indexImage = 0;
        } else {
            indexImage++;
        }
        SeeImageProject();
        System.out.println(indexImage);
    }

    public void Previous() {
        if (indexImage == 0) {
            indexImage = ImageProject().size() - 1;
        } else {
            indexImage--;
        }
        SeeImageProject();
        System.out.println(indexImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImageDa = new javax.swing.JLabel();
        panelRound1 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblSeeProject1 = new javax.swing.JLabel();
        lblSeeProject2 = new javax.swing.JLabel();
        lblSeeProject = new javax.swing.JLabel();
        lblSeeProject3 = new javax.swing.JLabel();
        lblSeeProject4 = new javax.swing.JLabel();
        lblSeeProject5 = new javax.swing.JLabel();
        lblSeeProject6 = new javax.swing.JLabel();
        lblSeeProject7 = new javax.swing.JLabel();
        lblSeeProject8 = new javax.swing.JLabel();
        lblSeeProject9 = new javax.swing.JLabel();
        btnExit = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblExit = new javax.swing.JLabel();
        btnEdit = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblEdit = new javax.swing.JLabel();
        btnProduct = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblProduct = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/imgAvartar/skye_bloom-black-removebg-preview.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setForeground(new java.awt.Color(255, 204, 51));

        lblImageDa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblImageDa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageDa.setText("Chưa có hình ảnh");
        lblImageDa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImageDa, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImageDa, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.setBackground(new java.awt.Color(255, 255, 153));

        lblSeeProject1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject1.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject2.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject3.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject4.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject5.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject6.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject7.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject8.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSeeProject9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject9.setForeground(new java.awt.Color(51, 51, 51));
        lblSeeProject9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeeProject, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addComponent(lblSeeProject1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblSeeProject, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeeProject8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSeeProject9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setRoundBottonLeft(40);
        btnExit.setRoundBottonRight(40);
        btnExit.setRoundTopLeft(40);
        btnExit.setRoundTopRight(40);

        lblExit.setBackground(new java.awt.Color(51, 51, 51));
        lblExit.setForeground(new java.awt.Color(0, 0, 0));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-left-arrow-30.png"))); // NOI18N
        lblExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEdit.setBackground(new java.awt.Color(153, 153, 153));
        btnEdit.setRoundBottonLeft(40);
        btnEdit.setRoundBottonRight(40);
        btnEdit.setRoundTopLeft(40);
        btnEdit.setRoundTopRight(40);

        lblEdit.setBackground(new java.awt.Color(51, 51, 51));
        lblEdit.setForeground(new java.awt.Color(0, 0, 0));
        lblEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-pencil-30.png"))); // NOI18N
        lblEdit.setText("Chỉnh sửa");
        lblEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnProduct.setBackground(new java.awt.Color(153, 153, 153));
        btnProduct.setRoundBottonLeft(40);
        btnProduct.setRoundBottonRight(40);
        btnProduct.setRoundTopLeft(40);
        btnProduct.setRoundTopRight(40);

        lblProduct.setBackground(new java.awt.Color(51, 51, 51));
        lblProduct.setForeground(new java.awt.Color(0, 0, 0));
        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-open-box-30.png"))); // NOI18N
        lblProduct.setText("Sản phẩm");
        lblProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnProductLayout = new javax.swing.GroupLayout(btnProduct);
        btnProduct.setLayout(btnProductLayout);
        btnProductLayout.setHorizontalGroup(
            btnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnProductLayout.setVerticalGroup(
            btnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-next-page-64.png"))); // NOI18N
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-back-to-64.png"))); // NOI18N
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPreviousMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext)
                            .addComponent(btnPrevious))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );

        add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code her
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-go-back-64.png"));
        Previous();
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void btnPreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseEntered
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-1-64.png"));
    }//GEN-LAST:event_btnPreviousMouseEntered

    private void btnPreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseExited
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-64.png"));
    }//GEN-LAST:event_btnPreviousMouseExited

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-circled-right-64.png"));
        Next();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-1-64.png"));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-64.png"));
    }//GEN-LAST:event_btnNextMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        NotesFrame.palAllMain.display(new ProjectFrame());
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        // TODO add your handling code here:
        EditProjectFrame editProjectFrame = new EditProjectFrame(da);
        editProjectFrame.setVisible(true);
    }//GEN-LAST:event_lblEditMouseClicked

    private void lblEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseEntered
        // TODO add your handling code here:
        btnEdit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblEditMouseEntered

    private void lblEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseExited
        // TODO add your handling code here:
        btnEdit.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblEditMouseExited

    private void lblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseClicked
        // TODO add your handling code here:
        NotesFrame.palAllMain.display(new ManagerProjectPanel(da));
    }//GEN-LAST:event_lblProductMouseClicked

    private void lblProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseEntered
        // TODO add your handling code here:
        btnProduct.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblProductMouseEntered

    private void lblProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseExited
        // TODO add your handling code here:
        btnProduct.setBackground(new Color(153, 153, 153));


    }//GEN-LAST:event_lblProductMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlbatdongsan.utils.PanelRound btnEdit;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnExit;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrevious;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblImageDa;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblSeeProject;
    private javax.swing.JLabel lblSeeProject1;
    private javax.swing.JLabel lblSeeProject2;
    private javax.swing.JLabel lblSeeProject3;
    private javax.swing.JLabel lblSeeProject4;
    private javax.swing.JLabel lblSeeProject5;
    private javax.swing.JLabel lblSeeProject6;
    private javax.swing.JLabel lblSeeProject7;
    private javax.swing.JLabel lblSeeProject8;
    private javax.swing.JLabel lblSeeProject9;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound1;
    private com.mycompany.qlbatdongsan.utils.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
