/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.TaiLieuDuAnDAO;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import com.mycompany.qlbatdongsan.Entity.TaiLieuDuAN;
import com.mycompany.qlbatdongsan.utils.XImage;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author HO VAN DAT
 */
public class SeeProjectFrame extends javax.swing.JFrame {

    TaiLieuDuAnDAO daoImage = new TaiLieuDuAnDAO();
    QuanLyDuAn da;
    private int indexImage;

    public SeeProjectFrame(QuanLyDuAn entity) {
        initComponents();
        this.da = entity;
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
        setTitle("HỆ THỐNG QUẢN LÝ BẤT ĐỘNG SẢN DVPTP");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        SeeProject();
        SeeImageProject();
        ImageProject();
        indexImage = setIndexImage();
    }

    public int setIndexImage() {
        if (ImageProject() != null) {
            return ImageProject().size() - 1;
        }
        return 0;
    }

    public List<TaiLieuDuAN> ImageProject() {
        List<TaiLieuDuAN> list = daoImage.selectByIdmaDA(da.getMaDA());
        if (list != null) {
            return list;
        }
        return list = new ArrayList<>();
    }

    public void SeeProject() {
        if (ImageProject().isEmpty()) {
            MsgBox.alert(this, "Dự án vẫn chưa có hình ảnh vui lòng thêm hình ảnh trong mục chỉnh sửa!!!");
            lblImageDa.setText("Vẫn chưa thêm hình ảnh!");
        }
        lblSeeProject.setText("Thông tin dự án: Dự án " + da.getTenDA() + " có Mã Dự Án " + da.getMaDA() + " thuộc loại Dự Án " + da.getLoaiDA() + " Ở địa chỉ " + da.getDiaChi());
        lblSeeProject1.setText("Với diện tích là " + da.getDienTich() + " cấp vào ngày " + da.getNgayCap() + " Nơi cấp ở " + da.getNoiCap() + " có giấy phép số " + da.getSoGiayPhep());
    }

    public void SeeImageProject() {
        for (int i = 0; i < ImageProject().size(); i++) {
            if (i == indexImage) {
                lblImageDa.setIcon(new ImageIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\imgAvartar\\" + ImageProject().get(i).getHinh()).getImage().getScaledInstance(850, 570, Image.SCALE_DEFAULT)));
            }
        }
    }

    public void Next() {
        if (indexImage == ImageProject().size() - 1) {
            indexImage = 0;
        } else {
            indexImage++;
        }
        SeeImageProject();
    }

    public void Previous() {
        if (indexImage == 0) {
            indexImage = ImageProject().size() - 1;
        } else {
            indexImage++;
        }
        SeeImageProject();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        btnEditProject = new javax.swing.JButton();
        btnExitProject = new javax.swing.JButton();
        btnOpenSPProject = new javax.swing.JButton();
        lblSeeProject1 = new javax.swing.JLabel();
        lblImageDa = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        lblSeeProject = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        btnEditProject.setText("Chỉnh sửa");
        btnEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProjectActionPerformed(evt);
            }
        });

        btnExitProject.setText("Thoát xem");
        btnExitProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitProjectActionPerformed(evt);
            }
        });

        btnOpenSPProject.setText("Sản phẩm dự án");
        btnOpenSPProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenSPProjectActionPerformed(evt);
            }
        });

        lblSeeProject1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject1.setForeground(new java.awt.Color(0, 0, 204));

        lblImageDa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblImageDa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageDa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-back-to-64.png"))); // NOI18N
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPreviousMouseExited(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-next-page-64.png"))); // NOI18N
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });

        lblSeeProject.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject.setForeground(new java.awt.Color(0, 0, 255));
        lblSeeProject.setText("Thông tin dự án : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOpenSPProject)
                        .addGap(28, 28, 28)
                        .addComponent(btnEditProject)
                        .addGap(26, 26, 26)
                        .addComponent(btnExitProject))
                    .addComponent(lblSeeProject1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeeProject, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addComponent(lblImageDa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnPrevious))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblImageDa, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblSeeProject, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSeeProject1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExitProject)
                    .addComponent(btnEditProject)
                    .addComponent(btnOpenSPProject))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitProjectActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn có chắc chắn muốn thoát")) {
            this.dispose();
        }

    }//GEN-LAST:event_btnExitProjectActionPerformed

    private void btnOpenSPProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenSPProjectActionPerformed
        // TODO add your handling code here:
        ManangerProjectFrame manangerProjectFrame = new ManangerProjectFrame(da);
        manangerProjectFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOpenSPProjectActionPerformed

    private void btnEditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProjectActionPerformed
        // TODO add your handling code here:
        EditProjectFrame editProjectFrame = new EditProjectFrame(da);
        editProjectFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditProjectActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-circled-right-64.png"));
        Next();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-1-64.png"));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-64.png"));
    }//GEN-LAST:event_btnNextMouseExited

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code her 
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-go-back-64.png"));
        Previous();
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void btnPreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseEntered
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-1-64.png"));
    }//GEN-LAST:event_btnPreviousMouseEntered

    private void btnPreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseExited
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-64.png"));
    }//GEN-LAST:event_btnPreviousMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProject;
    private javax.swing.JButton btnExitProject;
    private javax.swing.JLabel btnNext;
    private javax.swing.JButton btnOpenSPProject;
    private javax.swing.JLabel btnPrevious;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblImageDa;
    private javax.swing.JLabel lblSeeProject;
    private javax.swing.JLabel lblSeeProject1;
    // End of variables declaration//GEN-END:variables
}
