/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.NhanVienDAO;
import com.mycompany.qlbatdongsan.DAO.QuanLyDuAnDAO;
import com.mycompany.qlbatdongsan.DAO.SanGiaoDichDAO;
import com.mycompany.qlbatdongsan.DAO.TaiLieuDuAnDAO;
import com.mycompany.qlbatdongsan.Entity.NhanVien;
import com.mycompany.qlbatdongsan.Entity.QuanLyDuAn;
import com.mycompany.qlbatdongsan.Entity.SanGiaoDich;
import com.mycompany.qlbatdongsan.Entity.SanPhamDuAn;
import com.mycompany.qlbatdongsan.Entity.TaiLieuDuAN;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author HO VAN DAT
 */
public class SeeSPProjectPal extends javax.swing.JPanel {

    SanPhamDuAn SPDA;
    QuanLyDuAnDAO daoDA = new QuanLyDuAnDAO();
    TaiLieuDuAnDAO daoImage = new TaiLieuDuAnDAO();
    NhanVienDAO daoNV = new NhanVienDAO();
    SanGiaoDichDAO daoSGD = new SanGiaoDichDAO();
    private int indexImage;

    public SeeSPProjectPal(SanPhamDuAn entity) {
        initComponents();
        this.SPDA = entity;
        ImageProject();
        SeeProject();
        indexImage = setIndexImage();
        SeeImageProject();
        lblBackground.setIcon(new ImageIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\imgAvartar\\photo-1-15698192628241142777942.png").getImage().getScaledInstance(1340, 740, Image.SCALE_DEFAULT)));

    }

    public int setIndexImage() {
        if (ImageProject() != null) {
            return ImageProject().size() - 1;
        }
        return -1;
    }

    public List<TaiLieuDuAN> ImageProject() {
        List<TaiLieuDuAN> list = daoImage.selectByIdmaSPDA(SPDA.getMaSPDA());
        if (list != null) {
            return list;
        }
        return list = new ArrayList<>();
    }

    public void SeeProject() {
        if (ImageProject().isEmpty()) {
            MsgBox.alert(this, "Dự án vẫn chưa có hình ảnh vui lòng thêm hình ảnh trong mục chỉnh sửa!!!");
        }
        QuanLyDuAn da = daoDA.selectById(SPDA.getMaDA());
        NhanVien nv = daoNV.selectById(da.getMaNVPhuTrach());
        SanGiaoDich sgd = daoSGD.selectById(SPDA.getDonViPhanPhoi());
        lblSeeProject.setText("Sản phẩm "+ SPDA.getMaSPDA() +" thuộc dự án "+da.getTenDA()+ " kiểu nhà:  "+SPDA.getLoaiSP());
        lblSeeProject1.setText(SPDA.getTenSP().toUpperCase());
        lblSeeProject2.setText("Diện tích: " + SPDA.getDienTich() + "m2 ");
        lblSeeProject3.setText("SL phòng khách và nhà bếp: "+SPDA.getPhongBepKhach()+" phòng");
        lblSeeProject4.setText("SL phòng ngủ: "+SPDA.getPhongNgu()+" phòng");
        lblSeeProject5.setText("SL phòng WC: "+SPDA.getWC()+" phòng");
        lblSeeProject6.setText("Tiện nghi: "+SPDA.getTienNghi());
        
    
    }

    public void SeeImageProject() {
        for (int i = 0; i < ImageProject().size(); i++) {
            if (i == indexImage) {
                lblImageDa.setIcon(new ImageIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\imgAvartar\\" + ImageProject().get(i).getHinh()).getImage().getScaledInstance(850, 570, Image.SCALE_DEFAULT)));
                lblImageDa.setText(null);
            }
        }
    }

    public void Next() {
        if (indexImage == ImageProject().size() - 1) {
            indexImage = 0;
        } else {
            indexImage++;
        }
        SeeImageProject();
    }

    public void Previous() {
        if (indexImage == 0) {
            indexImage = ImageProject().size() - 1;
        } else {
            indexImage--;
        }
        SeeImageProject();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeeProject5 = new javax.swing.JLabel();
        lblSeeProject3 = new javax.swing.JLabel();
        lblSeeProject1 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        lblSeeProject4 = new javax.swing.JLabel();
        lblSeeProject = new javax.swing.JLabel();
        lblSeeProject2 = new javax.swing.JLabel();
        lblSeeProject6 = new javax.swing.JLabel();
        lblSeeProject8 = new javax.swing.JLabel();
        lblSeeProject9 = new javax.swing.JLabel();
        lblImageDa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnExit1 = new com.mycompany.qlbatdongsan.utils.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSeeProject10 = new javax.swing.JLabel();
        lblSeeProject11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeeProject5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject5.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 380, 27));

        lblSeeProject3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject3.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 380, 27));

        lblSeeProject1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblSeeProject1.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblSeeProject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 546, 72));

        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-back-to-64.png"))); // NOI18N
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPreviousMouseExited(evt);
            }
        });
        add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, -1));

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-next-page-64.png"))); // NOI18N
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });
        add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        lblSeeProject4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject4.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 380, 27));

        lblSeeProject.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 370, 27));

        lblSeeProject2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject2.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 380, 27));

        lblSeeProject6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject6.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 380, 27));

        lblSeeProject8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject8.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 380, 27));

        lblSeeProject9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject9.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 380, 30));

        lblImageDa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblImageDa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageDa.setText("Chưa có hình ảnh");
        lblImageDa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblImageDa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 640, 460));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SẢN PHẨM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 21, -1, -1));

        btnExit1.setBackground(new java.awt.Color(153, 153, 153));
        btnExit1.setRoundBottonLeft(40);
        btnExit1.setRoundBottonRight(40);
        btnExit1.setRoundTopLeft(40);
        btnExit1.setRoundTopRight(40);

        lblExit1.setBackground(new java.awt.Color(51, 51, 51));
        lblExit1.setForeground(new java.awt.Color(0, 0, 0));
        lblExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbatdongsan/images/icon/icons8-left-arrow-30.png"))); // NOI18N
        lblExit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExit1Layout = new javax.swing.GroupLayout(btnExit1);
        btnExit1.setLayout(btnExit1Layout);
        btnExit1Layout.setHorizontalGroup(
            btnExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnExit1Layout.setVerticalGroup(
            btnExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExit1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 650, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0,200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 720));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204,200));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 670, 20));

        lblSeeProject10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject10.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 380, 27));

        lblSeeProject11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSeeProject11.setForeground(new java.awt.Color(255, 255, 255));
        lblSeeProject11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblSeeProject11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 380, 27));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code her
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-go-back-64.png"));
        Previous();
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void btnPreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseEntered
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-1-64.png"));
    }//GEN-LAST:event_btnPreviousMouseEntered

    private void btnPreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseExited
        // TODO add your handling code here:
        btnPrevious.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-back-to-64.png"));
    }//GEN-LAST:event_btnPreviousMouseExited

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-circled-right-64.png"));
        Next();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-1-64.png"));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        // TODO add your handling code here:
        btnNext.setIcon(new ImageIcon("D:\\DuAn_1\\Duan1_QlBatDongSan\\src\\com\\mycompany\\qlbatdongsan\\images\\icon\\icons8-next-page-64.png"));
    }//GEN-LAST:event_btnNextMouseExited

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
        QuanLyDuAn da = daoDA.selectById(SPDA.getMaDA());
        NotesFrame.palAllMain.display(new ManagerProjectPanel(da));
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseEntered
        // TODO add your handling code here:
        btnExit1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblExit1MouseEntered

    private void lblExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseExited
        // TODO add your handling code here:
        btnExit1.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblExit1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlbatdongsan.utils.PanelRound btnExit;
    private com.mycompany.qlbatdongsan.utils.PanelRound btnExit1;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblImageDa;
    private javax.swing.JLabel lblSeeProject;
    private javax.swing.JLabel lblSeeProject1;
    private javax.swing.JLabel lblSeeProject10;
    private javax.swing.JLabel lblSeeProject11;
    private javax.swing.JLabel lblSeeProject2;
    private javax.swing.JLabel lblSeeProject3;
    private javax.swing.JLabel lblSeeProject4;
    private javax.swing.JLabel lblSeeProject5;
    private javax.swing.JLabel lblSeeProject6;
    private javax.swing.JLabel lblSeeProject8;
    private javax.swing.JLabel lblSeeProject9;
    // End of variables declaration//GEN-END:variables
}
