/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbatdongsan.ui;

import com.mycompany.qlbatdongsan.DAO.NhanVienDAO;
import com.mycompany.qlbatdongsan.DAO.SanGiaoDichDAO;
import com.mycompany.qlbatdongsan.Entity.CongNo;
import com.mycompany.qlbatdongsan.Entity.NhanVien;
import com.mycompany.qlbatdongsan.Entity.SanGiaoDich;
import com.mycompany.qlbatdongsan.utils.Auth;
import com.mycompany.qlbatdongsan.utils.MsgBox;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HO VAN DAT
 */
public class StaffFrame extends javax.swing.JPanel {
    NhanVienDAO dao = new NhanVienDAO();
    SanGiaoDichDAO daoSGD = new SanGiaoDichDAO();
    DefaultTableModel model;

    /**
     * Creates new form StaffFrame
     */
    public StaffFrame() {
        initComponents();
        initTableGuiSMS();
        initTableNhanVien();
        fillToTableNhanVien();
    }

    private void initTableNhanVien() {
        model = new DefaultTableModel();
        Object[] column = {"Mã số", "Họ và tên", "Ngày sinh", "Điện thoại", "Số nội bộ", "Chức danh", "Sàn giao dịch", "Quản lý", "Clock"};
        model.setColumnIdentifiers(column);
        model.setRowCount(0);
        tblNhanVien.setModel(model);
    }

    private void initTableGuiSMS() {
        model = new DefaultTableModel();
        Object[] column = {"STT", "Tên việc", "Tên thương hiệu", "Thời điểm", "Người tạo", "Người cập nhật", "Người gữi", "Kích hoạt"};
        model.setColumnIdentifiers(column);
        model.setRowCount(0);
        tblNhanVien.setModel(model);
    }
    
    public static void Search(String str) {
        if (str.length() > 0) {
            if (tblNhanVien!=null) {
                DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
                TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
                tblNhanVien.setRowSorter(trs);
                trs.setRowFilter(RowFilter.regexFilter(str));
            }else{
                return;
            }
        }
    }
    public void fillToTableNhanVien(){
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = null;
            if (Auth.user.getMaNV().equals("NV01")) {
                 list = dao.selectAll();
            }else{
                list = dao.selectBymaQuanLy(Auth.user.getMaNV());
                    }     
            for (NhanVien nv : list) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getHoTen(),
                    nv.getNgaySinh(),
                    nv.getSdt(),
                    nv.getSoNoiBo(),
                    nv.getChucDanh(),
                    daoSGD.selectById(nv.getMaSGD())==null?null:daoSGD.selectById(nv.getMaSGD()).getSanGiaoDich(),                   
                    dao.selectById(nv.getMaQuanLy())==null?null:dao.selectById(nv.getMaQuanLy()).getHoTen(),
                    nv.getLockCheckBox() 
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGuiSMS = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(255, 255, 255));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNhanVien);

        jLabel1.setText("Tạo việc  gữi SMS");

        tblGuiSMS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblGuiSMS);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("NHÂN VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(574, 574, 574)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 625, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblGuiSMS;
    private static javax.swing.JTable tblNhanVien;
    // End of variables declaration//GEN-END:variables
}
